[FIX] Switch-komponent
navikt/aksel pull request #1359
Opened 2021-12-13 10:39 UTC by KenAJoh

Figma: https://www.figma.com/file/3FfipnlMXUpxe6oH0EgxCG/?node-id=472%3A82

Erstatter #1250

2021-12-13 10:49 UTC, andnorda commented
La oss få denne inn i beta i Figma før vi merger den. Vil du pushe for det, @KenAJoh?

2021-12-13 11:27 UTC, KenAJoh commented
Ja kan ta en prat med Sjur

2021-12-21 08:47 UTC, KenAJoh commented
Er nå lagt til i Figma-beta. Merger den når alle tester er clear

2021-12-21 13:01 UTC, andnorda requested changes

2021-12-21 13:01 UTC, andnorda commented on @navikt/core/react/src/form/stories/switch.stories.tsx
> +      <Switch loader>Label text</Switch>
Propen heter loading. ;)

2021-12-21 13:01 UTC, andnorda commented on @navikt/core/react/src/form/Switch.tsx
> +        aria-describedby={(description && inputDescriptionId) || undefined}
Jeg tror ikke du trenger denne når label har `htmlFor`.

2021-12-21 13:01 UTC, andnorda commented on @navikt/core/react/src/form/Switch.tsx
> +        {loading && <Loader size="xsmall" />}
UX-spørsmål (trenger ikke svare på denne for å kunne merge): Burde loading switch være `disabled`?

2021-12-21 13:01 UTC, andnorda commented on @navikt/core/css/form/switch.css
> +  transform: translate(20px, -50%);
Bruk gjerne `translateX` her.

2021-12-21 13:01 UTC, andnorda commented on @navikt/core/css/form/switch.css
> +  border: none;
Trengs denne?

2021-12-21 13:01 UTC, andnorda commented on @navikt/core/react/src/form/Switch.tsx
> +      <span className="navds-switch__thumb">
For meg gir det mer mening at "thumb" ligger inni "track". Tenker du annerledes, eller er det en annen grunn til at du ikke har gjort det sånn?

2021-12-21 13:01 UTC, andnorda commented on @navikt/core/css/form/switch.css
> +  padding-left: 3.25rem;
UX-spørsmål: Burde vi standardisere plassering av beskrivelse i checkbox/radio/switch?
![image](https://user-images.githubusercontent.com/1894119/146932734-f3046567-7720-4e1d-9c85-0a1f3f27347c.png)
![image](https://user-images.githubusercontent.com/1894119/146932753-6bed8371-7fc2-4435-9d17-bbc50a2b5767.png)

2021-12-21 13:01 UTC, andnorda commented on @navikt/core/css/form/switch.css
> +}
Er det meningen at små switch med desc skal ha `padding-bottom`? (`.navds-switch--small > .navds-switch__label-wrapper > .navds-switch__content` har høyere spesifisitet enn `.navds-switch--with-description`)

2021-12-21 13:01 UTC, andnorda commented on @navikt/core/css/form/switch.css
> +}
Vi gikk forresten vekk fra å fjerne `padding-bottom` på checkboxer med desc, så det burde kanskje også samkjøres (igjen noe vi kan gjøre etter v1 er merget)

2021-12-21 13:01 UTC, andnorda commented on @navikt/core/css/form/switch.css
> +  appearance: none;
Trengs dette når `opacity` er 0?

2021-12-21 13:01 UTC, andnorda commented on @navikt/core/css/form/switch.css
> +  margin: 0;
Normalize fikser dette, så vet ikke om det er vits å definere det her.

2021-12-21 13:11 UTC, KenAJoh commented on @navikt/core/css/form/switch.css
> +  border: none;
Fjernet nå.

2021-12-21 13:14 UTC, KenAJoh commented on @navikt/core/react/src/form/Switch.tsx
> +      <span className="navds-switch__thumb">
Ingen spesiell grunn, skal gå greit å flytte den inn i `track`

2021-12-21 13:16 UTC, Sjur-NAV commented on @navikt/core/react/src/form/Switch.tsx
> +        {loading && <Loader size="xsmall" />}
Loading skjer mest sannsynlig når maskinen prøver å utføre handlingen til en bruker. Da skjer det i situasjonene fra Default til Active og fra Active til Default.

2021-12-21 13:18 UTC, Sjur-NAV commented on @navikt/core/css/form/switch.css
> +  padding-left: 3.25rem;
Jepp. Justerer design nå.

2021-12-21 13:18 UTC, KenAJoh commented on @navikt/core/css/form/switch.css
> +}
Var en miss her, ikke meningen at det skulle være padding-bottom med description. Fikset nå.

2021-12-21 13:20 UTC, KenAJoh commented on @navikt/core/css/form/switch.css
> +  appearance: none;
Nei, kan regnes som overflødig.

2021-12-21 13:26 UTC, KenAJoh commented on @navikt/core/css/form/switch.css
> +  padding-left: 3.25rem;
Fikset nå i kode

2021-12-21 13:30 UTC, KenAJoh commented on @navikt/core/css/form/switch.css
> +  margin: 0;
👍

2021-12-21 13:31 UTC, andnorda commented on @navikt/core/react/src/form/Switch.tsx
> +        {loading && <Loader size="xsmall" />}
Skal det går an å trykke på switch samtidig som den laster?

2021-12-21 13:44 UTC, andnorda approved these changes
LGTM 🎛 Bra jobba!

2021-12-21 13:48 UTC, merged

2021-12-21 14:31 UTC, Sjur-NAV commented on @navikt/core/css/form/switch.css
> +  padding-left: 3.25rem;
Nå er dette i sync i Figma.