[FEATURE] AccordionMenu -> Menu, diverse oppdateringer
navikt/aksel pull request #1392
Opened 2022-01-17 22:23 UTC by KenAJoh

- Rename til `Menu`, matcher figma og generell bruk av komponenten.
- Menu.Collapsible -> Menu.Drawer. Drawer er et relativt kjent konsept her, men kan hende collapsible/accordion gir mer mening?
- La til Menu.Link, hentet fra figma. Samme api som `Menu.Item`, bortsett fra ingen `active`-state.
- Oppdatert Css, løste nesting marerittet med React.context. `data-depth={context.depth + 1} blir satt på wrapper slik at man bruker verdien til å sette padding i CSS.

```css
// old
.navds-accordion-menu-collapsable
  .navds-accordion-menu-collapsable
  .navds-accordion-menu-collapsable
  .navds-accordion-menu-item,
.navds-accordion-menu-collapsable
  .navds-accordion-menu-collapsable
  .navds-accordion-menu-collapsable
  .navds-accordion-menu-collapsable
  .navds-accordion-menu-collapsable__button {
  padding-left: var(--navds-spacing-16);
}

// new 
[data-depth="3"] .navds-menu-drawer__button,
[data-depth="3"] .navds-menu-item {
  padding-left: var(--navds-spacing-14);
}
```

TODO: 
- [ ] React-router story i storybook klager, men feiler ikke. Kan hende jeg bare har misset noe veldig enkelt her.
```      
Property 'as' does not exist on type 'IntrinsicAttributes & MenuItemProps & RefAttributes<HTMLAnchorElement>'.
  Overload 2 of 2, '(props: { as: ForwardRefExoticComponent<NavLinkProps & RefAttributes<HTMLAnchorElement>>; } & MenuItemProps & Omit<...>): ReactElement<...>', gave the following error.
    Type '{ children: string; as: ForwardRefExoticComponent<NavLinkProps & RefAttributes<HTMLAnchorElement>>; activeClassName: string; to: string; }' is not assignable to type 'IntrinsicAttributes & { as: ForwardRefExoticComponent<NavLinkProps & RefAttributes<HTMLAnchorElement>>; } & MenuItemProps & Omit<...>'.
      Property 'activeClassName' does not exist on type 'IntrinsicAttributes & { as: ForwardRefExoticComponent<NavLinkProps & RefAttributes<HTMLAnchorElement>>; } & MenuItemProps & Omit<...>'.
```

2022-01-21 11:50 UTC, andnorda commented
Jeg kjenner drawer som noe annet: https://material.io/components/navigation-drawer. Har du noen eksempler på begrepet drawer bruket som her?

2022-01-21 11:54 UTC, andnorda commented
Jeg har snakket med Wei om at "Relaterte lenker" ikke hører hjemme i meny-komponenten. Hva tenker du, @KenAJoh ?

2022-01-21 11:59 UTC, KenAJoh commented
> Jeg har snakket med Wei om at "Relaterte lenker" ikke hører hjemme i meny-komponenten. Hva tenker du, @KenAJoh ?
Bare å fjerne den! Selv så jeg ikke helt grunnen til den men tok den med på grunn av Figma...

2022-01-21 12:04 UTC, KenAJoh commented
> Jeg kjenner drawer som noe annet: [material.io/components/navigation-drawer](https://material.io/components/navigation-drawer). Har du noen eksempler på begrepet drawer brukt som her?

Nei har ikke noe gode eksempler på bruk av drawer som funker her. Finner ikke en god definisjon på dette heller, så er åpne for forslag. Kanskje `Menu.Accordion` ?

2022-01-21 12:31 UTC, andnorda commented
Et problem med `Menu.Accordion` er at vi bruker samme begrep i `Accordion`-komponenten, og der betyr det en liste med ekspanderbare `AccordionItems`. Jeg stemmer for `Menu.Collapsible`.

2022-01-21 13:08 UTC, KenAJoh commented
> Et problem med `Menu.Accordion` er at vi bruker samme begrep i `Accordion`-komponenten, og der betyr det en liste med ekspanderbare `AccordionItems`. Jeg stemmer for `Menu.Collapsible`.

Ser den. Hva med bare `collapse`?

2022-01-21 13:20 UTC, andnorda commented
`Collapse` er supert!

2022-01-21 13:56 UTC, KenAJoh commented
Har nå fjernet `Menu.Link`, `background-color` på Menu og rename Drawer -> Collapse

2022-01-21 14:56 UTC, andnorda requested changes

2022-01-21 14:56 UTC, andnorda commented on @navikt/core/css/menu.css
> +  display: flex;
Overstyres av linje 44

2022-01-21 14:56 UTC, andnorda commented on @navikt/core/css/menu.css
> +  text-decoration: underline;
Overstyres av linje 46

2022-01-21 14:56 UTC, andnorda commented on @navikt/core/css/menu.css
> +  padding: 0;
Overstyres av linje 45

2022-01-21 14:56 UTC, andnorda commented on @navikt/core/css/menu.css
> +  color: var(--navds-menu-color);
Denne variabelen finnes ikke. Dessuten skal vel ikonet bare arve `color` fra knappen.

2022-01-21 14:56 UTC, andnorda commented on @navikt/core/css/menu.css
> +  display: inherit;
Jeg tenker `display: block` er ryddigere her, så den ikke plutselig arver en uønsket display.

2022-01-21 14:56 UTC, andnorda commented on @navikt/core/css/menu.css
> +[data-depth="1"] .navds-menu-collapse__button,
Disse er litt skumle da `data-depth` kan dukke opp i andre elementer i DOMen.
```suggestion
.navds-menu__list[data-depth="1"] .navds-menu-collapse__button,
```

2022-01-21 14:56 UTC, andnorda commented on @navikt/core/react/src/menu/Menu.tsx
> +  }
```suggestion
  ({ children, className, ...rest }, ref) => (
      <nav
        {...rest}
        role="navigation"
        ref={ref}
        className={cl("navds-menu", className)}
      >
        <MenuItems>{children}</MenuItems>
      </nav>
    )
```

2022-01-21 14:56 UTC, andnorda commented on @navikt/core/react/src/menu/MenuCollapse.tsx
> +      >
```suggestion
        {...rest}
        ref={ref}
        className={cl("navds-menu-collapse", className, {
          "navds-menu-collapse--open": isOpen,
        })}
      >
```

2022-01-21 14:56 UTC, andnorda commented on @navikt/core/react/src/menu/MenuCollapse.tsx
> +              data-depth={context.depth + 1}
Hva med den `NestingProvider` som tar seg av `+1`, så vi slipper å blande det inn i komponent-koden?

2022-01-22 17:22 UTC, KenAJoh commented on @navikt/core/css/menu.css
> +[data-depth="1"] .navds-menu-collapse__button,
True, fikset det

2022-01-25 14:13 UTC, andnorda approved these changes, later dismissed
LGTM

2022-01-28 09:17 UTC, merged