[fix] Read more component
navikt/aksel pull request #1456
Opened 2022-03-15 10:23 UTC by andnorda

2022-03-15 10:52 UTC, sarahbrodwall commented
- Hva betyr controlled/uncontrolled?
- Kan du legge en lenke inn i teksten i Storybook så vi kan verifisere at den ikke blir fokuserbar mens den er kollapset?

2022-03-15 11:03 UTC, andnorda commented
Controlled/uncontrolled er et konsept innen datahåndtering i React https://reactjs.org/docs/uncontrolled-components.html

Link er på plass i Storybook nå.

2022-03-15 12:40 UTC, sarahbrodwall commented
Godkjent fra uu sin side. :)

2022-03-15 14:49 UTC, KenAJoh commented on @navikt/core/css/read-more.css
> +
Mangler fokus-markering nå, får bare default outline. Kanskje bruke samme styling som lenker med blue-800 bakgrunn?

2022-03-15 14:50 UTC, KenAJoh commented on @navikt/core/css/read-more.css
> +.navds-read-more__expand-icon {
Bør ikonet ha samme hover-interaksjon som accordion der den blir "Filled" versjon ved hover?

2022-03-15 14:52 UTC, KenAJoh commented on @navikt/core/react/src/read-more/ReadMore.tsx
> +import { Collapse, UnmountClosed } from "react-collapse";
Hvis vi ikke skal ha med animasjon kan vi løse dette uten react-collapse vil jeg tro. Evt legge til samme animasjon som Accordion (kanskje bare 150ms da det er mye mindre innhold i read-only komponenten).
```
.navds-accordion .ReactCollapse--collapse {
    transition: height 250ms cubic-bezier(0.4, 0, 0.2, 1);
}
```

2022-03-15 14:57 UTC, KenAJoh commented on @navikt/core/css/read-more.css
> +  color: var(--navds-semantic-color-link);
Kan trekkes ut i en token

2022-03-15 14:57 UTC, KenAJoh requested changes
Noen småting som må ses på, men ellers ser det bra ut 🚀

2022-03-15 18:13 UTC, andnorda commented on @navikt/core/css/read-more.css
> +.navds-read-more__expand-icon {
Vi prøvde det, men det opplevdes litt voldsomt.

2022-03-15 18:16 UTC, andnorda commented on @navikt/core/css/read-more.css
> +  color: var(--navds-semantic-color-link);
Jeg tror det er sannsynlig at denne alltid vil være sammen farge som lenker, så da er jeg litt usikker på hva vi oppnår med å trekke den ut som en komponent-token. Hva tenker du er fordelen med det?

2022-03-15 18:17 UTC, andnorda commented on @navikt/core/css/read-more.css
> +
Ja, sant. Det glemte jeg.

2022-03-16 07:53 UTC, KenAJoh commented on @navikt/core/css/read-more.css
> +  color: var(--navds-semantic-color-link);
Fordelen er eks de som bygger sin egen darkmode/theming, men de kan også bare overskrive `navds-semantic-color-link` så trenger sikkert ikke trekke ut i token.

2022-03-16 16:01 UTC, sjbrodwall commented
Mulig å få noe easing i animasjonen?  Har vi en animasjon som er "vår"?

2022-03-16 16:03 UTC, KenAJoh approved these changes
LGTM 🚀

2022-03-16 16:08 UTC, andnorda commented
> Mulig å få noe easing i animasjonen? Har vi en animasjon som er "vår"?

Dette er animasjonen "vår" atm. Jeg kan gjerne endre den om du har et forslag. 

Vi trenger forøvrig å etablere en helhetlig animasjon-strategi for Nav, men noen andre kan få lov til å løfte den saken, for jeg har ikke båndbredde til det akkurat nå.

2022-03-16 16:09 UTC, merged

2022-03-16 16:11 UTC, sarahbrodwall commented
Animasjonstrategi...kanskje Martin-mat? Jeg tar det opp på Slack.