[FIX] React v18 upgrade
navikt/aksel pull request #1482
Opened 2022-04-03 12:43 UTC by KenAJoh

Tabs og ToggleGroup fungerer ikke i testing ved React v18 enda. Må undersøke nærmere hva som fører til dette før oppgradering til React 18 støtte.

2022-04-03 14:14 UTC, w3bdesign approved these changes, later dismissed

2022-04-04 07:01 UTC, andnorda approved these changes
LGTM 1️⃣8️⃣

2022-04-04 07:02 UTC, andnorda commented
Hmm, nei. Det ser ut som chechbox test brekker nå.

2022-04-04 07:03 UTC, andnorda requested changes
Hmm, nei. Det ser ut som chechbox test brekker nå.

2022-04-04 08:43 UTC, KenAJoh commented
> Hmm, nei. Det ser ut som chechbox test brekker nå.

Oppdaterte `@testing-library` for å støtte React v18. Oppdaterte også til `@testing-library/user-event` til v14 som endrer litt på hvordan man bruker user-events https://testing-library.com/docs/user-event/intro

2022-04-04 12:25 UTC, andnorda approved these changes
LGTM

2022-04-04 12:25 UTC, merged