Legger til bygging av typescript-komponentet og koverterer knapper (Closes #70)
navikt/aksel pull request #153
Opened 2017-11-29 12:58 UTC by etse

La til et oppsett for å bygge TypeScript-komponenter, og konverterte Knapper til typescript. I den forbindelse testet jeg om den bygde koden fungerte i FO-portefølje, hvor jeg fikk noen byggefeil. Årsaken til dette var at portefølje hadde feil i koden sin (brukte knappene feil), og de eksisterende definisjonstypene tillot dette.

Innfører også en breaking-change som kun vil påvirke folk som bruker TypeScript. Skal man sende inn type må man nå bruke enumen og ikke en string-verdi. Dette vil påvirke de som bruker TS - men tror det er et bedre pattern. Men vet ikke helt hvordan man skal håndtere det i fremtiden. For JS-brukere skal det være like som før.

Vil anbefale at man gjerne testet dette godt før man merger inn, spesielt med tanke på knapper i JS-applikasjoner.

Når denne blir merget skal det ligge til rette for å enkelt kunne konvertere flere komponenter til typescript fremover.

2017-11-29 16:05 UTC, nutgaard requested changes
🥇 Knallbra.
Har en par spørsmål though. :)

2017-11-29 16:05 UTC, nutgaard commented on packages/node_modules/nav-frontend-alertstriper/package.json
> +  "types": "lib/alertstripe.d.ts",
Vi vil vel fortsatt ha `jsnext:main` eller?

2017-11-29 16:05 UTC, nutgaard commented on packages/node_modules/nav-frontend-alertstriper/src/advarsel-alertstripe.tsx
> +function AlertStripeAdvarsel(props: AlertStripeProps) {
`function AlertStripeAdvarsel(props: AlertStripeProps): JSXElement {}` ? 
Da slipper du vel casting til `any` nedenfor også?

2017-11-29 16:05 UTC, nutgaard commented on packages/node_modules/nav-frontend-knapper/src/knapp.tsx
> +    htmlType?: 'submit' | 'button' | 'reset',
Hva får vi egentlig fra `CustomHTMLButtonAttributes` som vi ikke får fra `ButtonHTMLAttributes`?

2017-11-29 16:05 UTC, nutgaard commented on packages/node_modules/nav-frontend-knapper/src/knapp.tsx
> +class Knapp extends React.Component<KnappProps> { // eslint-disable-line react/prefer-stateless-function
Generelt angående propsTypes; må disse nå forvaltes som både en typescript- type og propTypes? Eller finnes det noen automatikk her?

2017-11-30 06:57 UTC, etse commented on packages/node_modules/nav-frontend-alertstriper/package.json
> +  "types": "lib/alertstripe.d.ts",
det finnes ikke noen jsnext lenger, er enten es5 eller TS. Og blir feil å la jsnext:main peke til noen av delene.

2017-11-30 06:59 UTC, etse commented on packages/node_modules/nav-frontend-knapper/src/knapp.tsx
> +class Knapp extends React.Component<KnappProps> { // eslint-disable-line react/prefer-stateless-function
Ikke finnet noe automatisk. På sikt hadde det beste vært å bare slette propTypes om majoriteten av prosjektene brukte TS. Men enn så lenge er det såpass mye prosjekter med ren JS at jeg tror å forvalte begge deler gir stor verdi.

2017-11-30 06:59 UTC, nutgaard commented on packages/node_modules/nav-frontend-alertstriper/package.json
> +  "types": "lib/alertstripe.d.ts",
True true. 😛

2017-11-30 07:01 UTC, etse commented on packages/node_modules/nav-frontend-knapper/src/knapp.tsx
> +    htmlType?: 'submit' | 'button' | 'reset',
type er av typen string i `ButtonHTMLAttributes`. Dette er ikke optimalt for oss, siden vi bruker den som en "enum" (valgte å ikke gjøre til enum siden det e breaking-change). 

Når man extender et interface har man ikke mulighet til å override typen til felter. (og når jeg leste issues andre har om dette virker det som at folk ikke ønsker å fikse det heller da det egentlig er en codesmell).

Skulle gjerne renamet `type` til `knappType` og gjort `htmlType` til `type`. Da slipper jeg å extende min egen custom-ting. Men det var en såpas stor breaking change at jeg valgte å la være.

2017-11-30 07:12 UTC, etse commented on packages/node_modules/nav-frontend-alertstriper/src/advarsel-alertstripe.tsx
> +function AlertStripeAdvarsel(props: AlertStripeProps) {
(finner ikke React.JSXElement) Ville trodd type-inferensen tok dette. Så litt etter gode løsninger. Fant ikke en optimal en. Men kan caste til noe mer fornuftig.

2017-11-30 07:13 UTC, etse commented on packages/node_modules/nav-frontend-alertstriper/src/advarsel-alertstripe.tsx
> +function AlertStripeAdvarsel(props: AlertStripeProps) {
Ville trodd type-inferensen skulle hjulpet her. Men tydeligvis ikke helt optimal. Og fikk ikke løsningen du foreslo.

Prøvde litt ulike ting, fant ikke en optimal løsning, men kan caste til noe mer fornuftig enn any.

2017-11-30 07:47 UTC, nutgaard commented on packages/node_modules/nav-frontend-alertstriper/src/advarsel-alertstripe.tsx
> +function AlertStripeAdvarsel(props: AlertStripeProps) {
Hvis vi hadde brukt `const AlertStripeAdvarsel = function(){}` syntaxen så ville det fungert. Men har sett det er par ganger nå at typescript ikke helt forstår seg på typene når det er vanlige funksjoner.

Ett alternativ er å skrive om til `React.PureComponent` og legge til `static propTypes = {};` i klassen.

2017-11-30 07:51 UTC, nutgaard commented on packages/node_modules/nav-frontend-knapper/src/knapp.tsx
> +    htmlType?: 'submit' | 'button' | 'reset',
Det har vært ett issue for flere opp igjennom. Var lite gjennomtenkt å bruke `type`-navnet her til å starte med. :( 

Men spørsmålet er om vi burde rydde opp i dette først som sist, e.g. innføre den endringen du nevner i siste avsnitt. @erlendev @frodehansen2 @helgefredheim @pederpus Tanker?

2017-11-30 07:52 UTC, nutgaard commented on packages/node_modules/nav-frontend-knapper/src/knapp.tsx
> +class Knapp extends React.Component<KnappProps> { // eslint-disable-line react/prefer-stateless-function
Fant noe som kanskje kunne løse noe av dette på interwebben i går. Men virker veldig uklart og litt shady. Så greieste er vel at vi bare forvalter begge frem til vi ser hvordan det går med adopsjonen av TypeScript her på huset.

2017-11-30 08:01 UTC, etse commented on packages/node_modules/nav-frontend-alertstriper/src/advarsel-alertstripe.tsx
> +function AlertStripeAdvarsel(props: AlertStripeProps) {
Å bruke const vil nok fungere fint her ja. Kan fint endre til det om det er ønskelig. Eneste problemet er at det kan føre til rare feil med tanke på hoisting (vært borti at det skjedde i portefølje). Tror årsaken egentlig var sirkulære avhengigheter hvor omskriving  til const gjør at det ikke blir hoista og man da ble avhengig av rekkefølgen til ble resolvet i. Så tror ikke det burde være noe issue her.

2017-11-30 08:02 UTC, nutgaard commented on packages/node_modules/nav-frontend-alertstriper/src/advarsel-alertstripe.tsx
> +function AlertStripeAdvarsel(props: AlertStripeProps) {
Jeg vil egentlig ikke ha `const`-syntaksen, men eneste grunnen til at jeg ikke liker den er pga at jeg synes det ser stygt ut. :P

2017-12-22 10:08 UTC, etse commented
Nå begynner denne pull-requesten å bli stor, og med de par som som skal merges inn i denne som ikke har approved enda så blir den enda større. Nærmer seg jo en egen HL. Tenker vi må få gått gjennom denne på nyåret og få merget den.

2017-12-22 10:08 UTC, closed without merging