Issue 160 Konverterer nav-frontend-etiketter til TS
navikt/aksel pull request #182
Opened 2017-12-19 11:18 UTC by marthejs

2017-12-22 09:49 UTC, etse requested changes
Vi trenger inne definisjonsfilene (*.d.ts), disse blir generert under bygging og lagt samme med den bygde koden.

2018-01-31 07:11 UTC, nutgaard commented
@marthejs Lyst til å titte litt mer på denne?

2018-02-06 11:30 UTC, etse approved these changes

2018-02-06 11:30 UTC, etse commented
@nutgaard slettet definisjonsfilene og oppdaterte PRen mot master.

2018-02-07 08:56 UTC, merged