Konvertere Hjelpetekst komponent til typescript
navikt/aksel pull request #184
Opened 2017-12-19 12:04 UTC by frodehansen2

Resolves #162

2017-12-22 09:54 UTC, etse requested changes
Vi trenger ikke definisjonsfilene. Disse blir laget av typescript-compileren under bygging og lagt sammen med de bygde filene. Bare pass på at types-feltet i package.json peker på den bygde definisjonsfilen.

2018-01-31 07:11 UTC, nutgaard commented
@etse @frodehansen2 Hva skjer med denne?

2018-02-06 11:52 UTC, etse commented
@nutgaard merget inn master og fikset conflicts. Fant også noen feil i alertstriper og spinneren som ble fikset. Så tenker denne burde merges fortest mulig :)

2018-02-06 11:52 UTC, etse approved these changes

2018-02-06 13:45 UTC, merged