Konverterer nav-frontend-grid til typescript
navikt/aksel pull request #187
Opened 2017-12-19 13:27 UTC by marthejs

2017-12-22 09:51 UTC, etse requested changes
Vi trenger ikke definisjonsfilene. Disse blir laget av typescript-compileren under bygging og lagt sammen med de bygde filene. Bare pass på at types-feltet i package.json peker på den bygde definisjonsfilen.

2018-01-31 07:09 UTC, nutgaard commented
@marthejs Har du mulighet til å titte på denne?

2018-02-21 11:06 UTC, etse approved these changes

2018-02-21 12:05 UTC, nutgaard approved these changes

2018-02-21 12:05 UTC, nutgaard commented on packages/node_modules/nav-frontend-grid/src/column.tsx
> +    children?: React.ReactNode | React.ReactChild | React.ReactChildren |
Må egentlig `children` være med? Trodde de la implisitt med.

2018-02-21 12:07 UTC, nutgaard submitted a review, later dismissed

2018-02-21 12:07 UTC, nutgaard commented on packages/node_modules/nav-frontend-grid/package.json
> +  "types": "lib/grid.d.ts",
Bump major

2018-02-21 12:25 UTC, etse commented
@nutgaard oppdatert etter tilbakemeldinger :)

2018-02-21 15:12 UTC, nutgaard requested changes

2018-02-21 15:12 UTC, nutgaard commented on packages/node_modules/nav-frontend-grid/src/container.tsx
> +    children?: React.ReactNode | React.ReactChild | React.ReactChildren |
Flere `children` tror det ligger i flere filer her. ;)

2018-02-21 15:12 UTC, nutgaard commented on packages/node_modules/nav-frontend-grid/src/row.tsx
> +    children: React.ReactNode | React.ReactChild | React.ReactChildren |
children

2018-02-22 15:27 UTC, nutgaard approved these changes

2018-02-28 08:36 UTC, merged