Legger til alle Streamline-ikoner som webfonter
navikt/aksel pull request #205
Opened 2018-02-01 12:37 UTC by Lillebo

Har konvertert alle ikoner i Streamline-pakken til webfonter som enkelt kan importeres og brukes som et alternativ til SVG-ikoner.

Fontene bruker [ligatures](https://en.wikipedia.org/wiki/Typographic_ligature) for å rendre de forskjellige ikonene, og vil fungere på akkurat samme måte som [Google sine Material Icons](https://material.io/icons/).

For å ta disse i bruk trenger man kun å importere pakken `nav-frontend-ikoner-webfont-style` og opprette et element med klasse `nav-ikoner <type> <gruppe>` og med tekst-innhold som svarer til nøkkelordet for ikonet man ønsker å bruke. Tekst-innholdet vil da rendres som et ikon.

Type er enten `filled` eller `line`, mens gruppe er ikon-gruppen ikonet tilhører. Nøkkelordene er filnavnene til ikonene slik de ligger i Streamline-pakken (men med `_` delimiter). En oversikt over alle grupper, hvilke ikoner som hører til hvilken gruppe og deres nøkkelord finner dere inntil videre [her](https://gist.github.com/Lillebo/612b36efda7cd1cc210a3ef0f812932b) (mer om dette lengre ned).

**Eksempel:**

```
import 'nav-frontend-ikoner-webfont-style';

<div class="nav-ikoner filled edition">binoculars</div>
<div class="nav-ikoner line design">check_list</div>
```

Koden ovenfor vil importere alle webfontene og rendre et fylt kikkert-ikon og et linjet sjekkliste-ikon.

**Annet eksempel:**

```
import 'nav-frontend-ikoner-webfont-style/src/line/edition/font.less';

<div class="nav-ikoner line edition">binoculars</div>
```

Koden ovenfor vil bare importere webfonten for edition-gruppen, og rendre et linjet kikkert-ikon.

## Ikon-bibliotek

Dette er første ledd i et forsøk på å bygge et fullverdig ikon-bibliotek på designsystem-siden hvor brukere kan se alle ikoner, søke frem ikoner man leter etter, og laste ned disse (enten som webfont, SVG eller PNG). Har laget en skisse for hvordan en slik side kan se ut:

<img width="1187" alt="screen shot 2018-02-01 at 09 03 07" src="https://user-images.githubusercontent.com/74510/35678490-e3f7f1a2-0753-11e8-9aa9-dd742bc89d0e.png">

Ved klikk på et ikon vil bruker få informasjon om hvilken import-path man må bruke, og et eksempel på HTML-kode som rendrer det gitte ikonet (med type, gruppe-navn og nøkkelord ferdig utfylt).

Tanker og innspill mottas med takk :)

2018-02-01 15:17 UTC, nutgaard approved these changes

2018-02-07 08:16 UTC, erlendev requested changes
Avventer svar på avklaringer imorgen før denne kan merges.

2018-02-08 09:27 UTC, etse approved these changes

2018-07-23 12:44 UTC, Lillebo commented
Erstattes av alternativ løsning.

2018-07-23 12:44 UTC, closed without merging