Legger til Veileder-komponent
navikt/aksel pull request #210
Opened 2018-02-13 12:29 UTC by Lillebo

Veileder er et slags illustrasjons-portrett av en NAV-veileder som snakker til brukeren. Komponenten kan brukes som et personlig støtte-element som gir råd, tips og tilbakemelding underveis i søknader og andre komplekse prosesser.

Komponenten kan rendres i vilkårlig størrelse, og vil skalere proporsjonalt avhengig av størrelse-attributtet 'width'.

<img width="1106" alt="screen shot 2018-02-13 at 12 03 57" src="https://user-images.githubusercontent.com/74510/36149593-a0e7c7c2-10c0-11e8-8ee5-6c1600d9bbbc.png">

2018-02-13 13:20 UTC, erlendev requested changes
Noen kommentarer her

2018-02-13 13:20 UTC, erlendev commented on packages/node_modules/nav-frontend-veileder/package.json
> +  "publishConfig": {
Disse `publishConfig`- og `repository`--attributtene tror jeg kan fjernes. Antagelig noe utdatert i scaffolding-scriptene her.

2018-02-13 13:20 UTC, erlendev commented on packages/node_modules/nav-frontend-veileder/package.json
> +  "publishConfig": {
Evt. kan repository erstattes med faktisk repository-url på github :)

2018-02-13 13:20 UTC, erlendev commented on packages/node_modules/nav-frontend-veileder/src/veileder.tsx
> +            transform: 'scale(' + scaleMultiplier + ')' // eslint-disable-line prefer-template
Denne eslint-feilen tror jeg du kan fikse med med å si `scale(${scaleMultiplier})` med `-fnutter rundt (GitHub fjerner fra kodeksemplet).

2018-02-13 13:20 UTC, erlendev commented on packages/node_modules/nav-frontend-veileder/src/veileder.tsx
> +            width,
Disse ubrukte variablene kan vel fjernes fra render-funksjonen?

2018-02-13 13:20 UTC, erlendev commented on packages/node_modules/nav-frontend-veileder/src/veileder.tsx
> +                {renderChatBubble(says, width, chatBubbleStyles, chatBubbleArrowStyles, chatBubbleProps)}
renderChatBubble ser ut som noe som burde kodes/brukes som en React-komponent :)

2018-02-13 13:20 UTC, erlendev commented on packages/node_modules/nav-frontend-veileder/src/veileder.tsx
> +(Veileder as any).defaultProps = {
Trenger vi å sette defaultProp=undefined på ting som ikke er required?

2018-02-13 13:20 UTC, erlendev commented on packages/node_modules/nav-frontend-veileder/src/veileder.tsx
> +const renderChatBubble = (says, width, chatBubbleStyles, chatBubbleArrowStyles, chatBubbleProps) => {
Er disse `chatBubbleArrowStyles` og `chatBubbleStyles` noe vi egentlig trenger og/eller vil at folk skal kunne endre på gjennom apiet til komponenten? Tenker kanskje det er naturlig at det er noe folk må customize i sin egen styling enn at vi skal tråkke opp løypa for dem med bruk av inline-styling via. React.

Er også litt usikker på chatBubbleProps som spreades ut på en div, er det noe vi trenger? `aria-label`s f.eks.  burde vel settes av utviklerne selv i `says` som er en React-komponent.

2018-02-13 13:47 UTC, Lillebo commented on packages/node_modules/nav-frontend-veileder/src/veileder.tsx
> +            width,
Hm, tror jeg må hente de ut der for at de ikke skal spres utover som HTML-attributter på `div.nav-frontend-veileder`

2018-02-13 13:55 UTC, Lillebo commented on packages/node_modules/nav-frontend-veileder/src/veileder.tsx
> +                {renderChatBubble(says, width, chatBubbleStyles, chatBubbleArrowStyles, chatBubbleProps)}
Hm, litt usikker på hva gevinsten vil være? Kan fort bli litt forvirrende om vi eksponerer flere "snakkeboble"-komponenter?

2018-02-13 13:58 UTC, Lillebo commented on packages/node_modules/nav-frontend-veileder/src/veileder.tsx
> +const renderChatBubble = (says, width, chatBubbleStyles, chatBubbleArrowStyles, chatBubbleProps) => {
Hm, godt poeng 👍

2018-02-14 07:11 UTC, erlendev commented on packages/node_modules/nav-frontend-veileder/src/veileder.tsx
> +                {renderChatBubble(says, width, chatBubbleStyles, chatBubbleArrowStyles, chatBubbleProps)}
Tenkte ikke egentlig at vi trengte å eksportere den ut som en del av modulen, men at vi gjør det internt i komponenten for lesbarhetens skyld. Selvfølgelig ikke noe vi _må_ gjøre, men i praksis er det jo egentlig en React-komponent allerede, bare at den kalles som en funksjon med parametere istedetfor med vanlig bruk av JSX/props.

2018-02-14 07:43 UTC, erlendev commented on packages/node_modules/nav-frontend-veileder/src/veileder.tsx
> +            width,
Ok, skjønner hvorfor du løser det sånn, men det er en litt snodig bruk av spread-operatoren imo siden det fører til ubrukte variabler i komponenten og derav eslint-feil som vi må fjerne med eslint-disables. Et alternativ her for å få det litt mer elegant kunne være å bruke `omit` fra js-utils-modulen som egentlig løser dette for oss. :)

2018-02-15 07:32 UTC, erlendev approved these changes

2018-02-15 07:38 UTC, merged