Konverterer lukknapp til typescript
navikt/aksel pull request #222
Opened 2018-02-21 11:29 UTC by etse

Resolves #164

2018-02-21 12:07 UTC, nutgaard submitted a review, later dismissed

2018-02-21 12:07 UTC, nutgaard commented on packages/node_modules/nav-frontend-lukknapp/package.json
> +  "types": "lib/lukknapp.d.ts",
Bump major

2018-02-21 15:14 UTC, nutgaard approved these changes

2018-02-22 07:32 UTC, Lillebo requested changes

2018-02-22 07:32 UTC, Lillebo commented on packages/node_modules/nav-frontend-lukknapp/src/lukknapp.tsx
>  import PT from 'prop-types';
Hm, får runtime feil hvis denne ikke importeres som `import { PropTypes as PT } from 'prop-types';`

2018-02-22 08:35 UTC, etse commented on packages/node_modules/nav-frontend-lukknapp/src/lukknapp.tsx
>  import PT from 'prop-types';
rart man ikke får build-time feil på dette :/

2018-02-22 08:37 UTC, Lillebo commented on packages/node_modules/nav-frontend-lukknapp/src/lukknapp.tsx
>  import PT from 'prop-types';
Yup

2018-02-22 08:37 UTC, Lillebo approved these changes

2018-03-07 08:55 UTC, merged