Bump versjonen til react-modal.
navikt/aksel pull request #231
Opened 2018-02-28 15:06 UTC by LarsAndreasNav

Jeg vil bumpe fordi versjon ^2.2.4 har peer-dependencies til eldre versjon av blant annet react. Jeg fant ingen beskrivelse av forskjellen mellom 2.*.* og 3.*.*, men jeg gjorde en enkel test av komponenten med den nye pakken, og det gikk fint.

2018-02-28 15:19 UTC, nutgaard requested changes

2018-02-28 15:19 UTC, nutgaard commented on package.json
> +    "react-modal": "^3.3.1",
Vi bør fortsatt støtte 2.x.x-versjonen, så bruk gjerne `^2.2.4 || ^3.0.0`

2018-02-28 15:19 UTC, nutgaard commented on packages/node_modules/nav-frontend-modal/package.json
> +    "react-modal": "^3.3.1"
Vi bør fortsatt støtte 2.x.x-versjonen, så bruk gjerne `^2.2.4 || ^3.0.0`.

2018-02-28 15:21 UTC, nutgaard commented
Bruk av react-modal@3.x.x skal forsåvidt fungere allerede idag, men man vil få en feilmelding ved `npm install` pga feil versjon i forhold til peer-dependencies. I all hovedsak så er det bare `peerDependencies` i nav-frontend-modal som må endres, men synes det er greit å ta endringene de andre stedene også for å signalisere litt bredere at vi støtter begge versjoner.

2018-02-28 15:47 UTC, nutgaard requested changes

2018-02-28 15:47 UTC, nutgaard commented on package.json
> +    "react-modal": "^2.4.4 || ^3.3.1",
Skriveleif på 2.x.x versjonen? Eller er det meningen med bump av minor og patch? :)
(Gjelder alle tre stedene)

2018-03-05 07:12 UTC, LarsAndreasNav commented on package.json
> +    "react-modal": "^2.4.4 || ^3.3.1",
Oi, der hadde det sneket seg inn et firetall, ja!

2018-03-05 07:38 UTC, nutgaard approved these changes

2018-03-05 07:39 UTC, merged