[Datepicker/Modal] Datepicker bruker nå Modal på mobil og for nested Modal
navikt/aksel pull request #2419
Opened 2023-10-25 10:43 UTC by KenAJoh

### Change summary

- Datepicker/Monthpicker bytter nå til Modal på max-width `780px`
- Bruk av Datepicker/Monthpicker i Modal åpnes nå i egen Modal automatisk, ikke Popover
- Trukket kode for Popover/Modal-switch ut i egen `DateWrapper`-komponent (for internt bruk)
- Fjernet `openOnFocus`-prop da man bare kan åpne Popover/Modal ved klikk på knapp
- Bruker nå native `onClose` fra Popover/Modal for lukking ved outside-click eller ESC. Fjernet da `useEscape` og `useOutsideClick`
- Flyttet forwarded-ref til datepicker-wrapper fra Popover
- La til `useMedia`-hook som lytter på mediaqueries (for å bytte mellom Popover og Modal on-the-fly)
- Fjernet Eksempler for Datepicker i Modal da vi ikke vil oppmuntre til det

2023-10-31 11:58 UTC, HalvorHaugan requested changes

2023-10-31 11:58 UTC, HalvorHaugan commented on @navikt/core/react/src/date/hooks/useDatepicker.tsx
>    openOnFocus?: boolean;
Kan eventuelt også gjøre dette i tilfelle noen ikke får med seg at den er deprecated? (Brekker ikke siden ingen setter den til true i dag?)
```suggestion
  openOnFocus?: false;
```

2023-10-31 11:58 UTC, HalvorHaugan commented on @navikt/core/react/src/date/hooks/useMonthPicker.tsx
> +   * Will be removed in a future major-versionfuture versions
```suggestion
   * Will be removed in a future major-version
```

2023-10-31 11:58 UTC, HalvorHaugan commented on @navikt/core/react/src/date/datepicker/datepicker.stories.tsx
>  };
Storyen ModalDemo blir blank i snapshot. Tror det bare er å legge til dette:
```suggestion
};
ModalDemo.parameters = { chromatic: { pauseAnimationAtEnd: true } };
```

2023-10-31 11:58 UTC, HalvorHaugan commented on @navikt/core/react/src/date/datepicker/datepicker.stories.tsx
Litt utenfor scope, men foreslår at Size-storyen har forhåndsutfylte felt, slik at vi får det med på snapshot.

2023-10-31 11:58 UTC, HalvorHaugan commented on @navikt/core/react/src/date/parts/DateWrapper.tsx
> +      className="navds-date--polyfilled-nested"
Synes det blir feil å ta med "polyfilled" i klassenavnet når klassen blir satt uansett. Hva med noe sånt: `navds-date__nested-modal`

2023-10-31 11:58 UTC, HalvorHaugan commented on @navikt/core/react/src/date/datepicker/DatePicker.tsx
> +    const mergedRef = useMemo(() => mergeRefs([wrapperRef, ref]), [ref]);
Sjekket at dette ikke brekker noe for noen?

2023-10-31 11:58 UTC, HalvorHaugan commented on @navikt/core/react/src/date/hooks/useDatepicker.tsx
> +      /* inputRef.current && inputRef.current.focus(); */
Var det meningen å kommentere ut dette?

2023-10-31 11:58 UTC, HalvorHaugan commented on @navikt/core/react/src/date/parts/DateWrapper.tsx
> +        onClose={() => onClose()}
```suggestion
        onClose={onClose}
```

2023-10-31 11:58 UTC, HalvorHaugan commented on @navikt/core/react/src/date/parts/DateWrapper.tsx
> +      onClose={() => onClose()}
```suggestion
      onClose={onClose}
```

2023-10-31 11:58 UTC, HalvorHaugan commented on @navikt/core/react/src/date/parts/DateWrapper.tsx
> +        <Button variant="tertiary" onClick={() => onClose()} size="small">
```suggestion
        <Button variant="tertiary" onClick={onClose} size="small">
```

2023-10-31 11:58 UTC, HalvorHaugan commented on @navikt/core/react/src/date/utils/labels.ts
> +      return `Velg start og sluttdato`;
```suggestion
    case "nb":
      return `Velg start- og sluttdato`;
    case "nn":
      return `Vel start- og sluttdato`;
    case "en-GB":
      return `Pick a start and end date`;
    default:
      return `Velg start- og sluttdato`;
```

2023-10-31 11:58 UTC, HalvorHaugan commented on @navikt/core/react/src/modal/Modal.tsx
> +    if (modalContext && !dateContext) {
`dateContext` er alltid et objekt

2023-10-31 11:58 UTC, HalvorHaugan commented on @navikt/core/react/src/popover/Popover.tsx
> +    const chosenFlip = isInDatepicker ? false : _flip;
Date-konteksten er alltid et objekt.

Btw, hvorfor er chromatic disabled på popover.stories?

2023-10-31 11:58 UTC, HalvorHaugan commented on @navikt/core/react/src/util/useMedia.ts
> +        return;
Trengs den ytterste if-en?

2023-10-31 11:58 UTC, HalvorHaugan commented on @navikt/core/react/src/util/useMedia.ts
> +  const [isActive, setIsActive] = useState(defaultFallback ?? false);
Er det ikke ryddigst at `isActive` ikke får noen fallback når `defaultFallback` ikke er definert? (Altså fjerne `?? false`)

2023-10-31 11:58 UTC, HalvorHaugan commented on @navikt/core/react/src/util/useMedia.ts
> +  const [isActive, setIsActive] = useState(defaultFallback ?? false);
Noen navngivningsforslag (ikke viktig):
- `defaultFallback` -> `initialValue` eller `fallback`
- `isActive` -> `matches` eller `doesMatch`

2023-10-31 11:58 UTC, HalvorHaugan commented on @navikt/core/react/src/util/useMedia.ts
> +        mediaQueryList.removeEventListener("change", listener);
Er det nødvendig å sjekke `noMatchMedia` igjen her?

2023-10-31 15:56 UTC, KenAJoh commented on @navikt/core/react/src/util/useMedia.ts
> +        return;
Nope, bøt ikke trengs 🚀

2023-10-31 15:56 UTC, KenAJoh commented on @navikt/core/react/src/util/useMedia.ts
> +  const [isActive, setIsActive] = useState(defaultFallback ?? false);
Done 🚀

2023-10-31 15:57 UTC, KenAJoh commented on @navikt/core/react/src/util/useMedia.ts
> +        mediaQueryList.removeEventListener("change", listener);
Er for å ikke kjøre unødvendig `removeEventListener`

2023-10-31 15:57 UTC, KenAJoh commented on @navikt/core/react/src/util/useMedia.ts
> +  const [isActive, setIsActive] = useState(defaultFallback ?? false);
Enig, fikset 👍

2023-10-31 15:58 UTC, KenAJoh commented on @navikt/core/react/src/popover/Popover.tsx
> +    const chosenFlip = isInDatepicker ? false : _flip;
Fikset 👍 
Stories på popover ble slått av da de var veldig flaky. Kan hende chromatic/floating-ui er bedre nå slik at de kan enables igjen

2023-10-31 16:00 UTC, KenAJoh commented on @navikt/core/react/src/date/datepicker/datepicker.stories.tsx
God idè, fikset

2023-11-01 08:45 UTC, KenAJoh commented on @navikt/core/react/src/date/datepicker/DatePicker.tsx
> +    const mergedRef = useMemo(() => mergeRefs([wrapperRef, ref]), [ref]);
Har bare funnet `ref` satt på `DatePicker.Input` til nå 👍

2023-11-01 08:53 UTC, KenAJoh commented on @navikt/core/react/src/modal/Modal.tsx
> +    if (modalContext && !dateContext) {
Har gjort `dateContext` til default null nå 👍

2023-11-01 13:50 UTC, KenAJoh commented on @navikt/core/react/src/date/hooks/useDatepicker.tsx
> +      /* inputRef.current && inputRef.current.focus(); */
Fikset 🚀

2023-11-01 14:22 UTC, HalvorHaugan submitted a review, later dismissed

2023-11-01 14:38 UTC, merged