Fjerner / ved import fra nodeModulesPath/coreModulePath slik at det f…
navikt/aksel pull request #25
Opened 2017-06-26 12:51 UTC by helgefredheim

…unker med ~. Dette er nyttig ved bruk av webpack/less-loader.

2017-06-26 13:01 UTC, nutgaard commented
Løser #24 men trenger minor-bump på pakker og oppdaterte eksempler.

2017-06-26 13:02 UTC, nutgaard requested changes
minor-bump på pakkene
og gjerne oppdaterte webpack-eksempler i /examples

2017-06-27 06:52 UTC, helgefredheim commented
@nutgaard: Da skal eksempler være oppdatert og pakkene være minor-bumpa.

2017-06-27 07:24 UTC, erlendev approved these changes

2017-06-27 08:36 UTC, nutgaard approved these changes
Supert. 👍

2017-06-27 09:06 UTC, merged