:bug: fix templates examples
navikt/aksel pull request #2507
Opened 2023-11-22 15:44 UTC by JulianNymark

bugfix (new templates have been generated in prod already, this is the code that did it)

2023-11-23 11:00 UTC, KenAJoh requested changes
`withDsExample` var ikke brukt i templates siden den legger på ekstra styling vi ikke ønsker. Må endten ikke bruke `withDsExample` eller legge til en ny variant 
```
export default withDsExample(Example, { variant: "template" });
```
som ikke legger på noen styling

2023-11-23 13:42 UTC, JulianNymark commented
> `withDsExample` var ikke brukt i templates siden den legger på ekstra styling vi ikke ønsker. Må endten ikke bruke `withDsExample` eller legge til en ny variant

Stemmer, det var de som gjorde at de så cleanere ut... lager en ny HOC `withDsTemplate` tenker jeg, og scanner etter begge to i filter-code 🚀

2023-11-23 14:16 UTC, JulianNymark commented
Ny tanke, burde vi i stedet for å lete etter kode lete etter en streng? noe à la `// EXAMPLES DO NOT INCLUDE CONTENT BELOW THIS LINE`. + throw error om den ikke finner kommentar?

2023-11-23 14:22 UTC, KenAJoh commented
> Ny tanke, burde vi i stedet for å lete etter kode lete etter en streng? noe à la `// EXAMPLES DO NOT INCLUDE CONTENT BELOW THIS LINE`. + throw error om den ikke finner kommentar?

Har funket det også 👍

2023-11-23 15:09 UTC, JulianNymark commented
btw, vil ha din input på `aksel.nav.no/website/.storybook/main.ts` i storyIndexers, ser den også matchet på withDsExample så den brekker nok, har ikke satt meg mye inn i denne kode snutten enda, kan sikkert ta en kjapp huddle på det :)

2023-11-24 14:49 UTC, KenAJoh commented
> btw @KenAJoh , vil ha din input på `aksel.nav.no/website/.storybook/main.ts` i storyIndexers, ser den også matchet på withDsExample så den brekker nok, har ikke satt meg mye inn i denne kodesnutten enda, kan sikkert ta en kjapp huddle på det :)

Alle "pages" i next trenger en default export som er siden som vises. I storybook er alle stories names exports, mens configen er default export. For denne PR-en vil `aksel.nav.no/website/.storybook/main.ts` fungere som før da eksemplene ikke er endret på. Templates blir at the moment ikke vist i storybook, så trenger ikke tilpasse den casen her enda

2023-11-27 15:35 UTC, KenAJoh approved these changes, later dismissed

2023-11-27 21:51 UTC, KenAJoh approved these changes
Kommenterte ut testing av templates i sandbox for nå slik at vi kan vise templates i sandbox på mal-sider.

2023-11-28 11:41 UTC, merged