Erstatte spinner med ny anminasjon
navikt/aksel pull request #271
Opened 2018-05-11 08:46 UTC by jcpgithub

PR'en
Sjekke om det er ok, eller om jeg har glemt noe...?

2018-05-11 09:36 UTC, nutgaard commented on packages/node_modules/nav-frontend-spinner-style/src/spinner-style.less
> +  .spinner-div-mixin(xxxl, 256px, 24.4px, 23px, 197px);
Alle disse pixel-verdiene virker veldig magisk. Spesielt 24.4px.

2018-05-11 09:36 UTC, nutgaard commented on packages/node_modules/nav-frontend-spinner-style/src/spinner-style.less
> +  .spinner-div-mixin(l, 40px, -7px, -9px, 13px);
Hvor har det blitt av alle de små variantene?

2018-05-11 09:38 UTC, nutgaard commented on packages/node_modules/nav-frontend-spinner-style/src/spinner-style.less
> +    border-color: #CCDEE6 transparent transparent transparent;
Denne fargen har veldig dårlig kontrast mot hvit/navGra bakgrunn. Er dette testet/tenkt på fra designers side?

2018-05-11 09:43 UTC, nutgaard requested changes
Major-breaking change siden flere størrelser fjernes, må evt. støtte tidligere størrelser eller bumpe major.

Er litt ikoner som kan slettes unna, siden det bare er spinneren som bruker de.

Stor endring visuelt. Er dette forankret hos designsystemteamet?

2018-05-11 09:46 UTC, nutgaard commented
**Eksisterende:**
![image](https://user-images.githubusercontent.com/1413417/39918463-cdf8a18e-5510-11e8-9667-af3852b7627a.png)

**PR:**
![image](https://user-images.githubusercontent.com/1413417/39918436-b5d68102-5510-11e8-80a0-f542dceffffc.png)

Alltid fint med bilder, når det er visuelle endringer.

2018-05-11 10:10 UTC, sergiohaisch commented
Kan man se den noen sted, ikke  i screenshots her? virker litt lys og lurer på om kontrasten går gjennom Wcag.

2018-05-11 10:14 UTC, Lillebo commented
Takk for PR 🙂

Endringen av spinner er forankret i Designsystem-teamet. Men vi må nok fortsatt støtte de samme størrelsene som forrige versjon ja, så `m`, `s`, `xs` og `xxs` må med her også. Her tror jeg også vi må se litt på hvordan spinneren skalerer mellom de forskjellige størrelsene. Jeg tror ikke vi kan beholde samme tykkelse på sirkelen etterhvert som den minker/øker. Jeg tror nok noe slikt er mer i tråd med slik det bør være:
<img width="601" alt="spinner" src="https://user-images.githubusercontent.com/74510/39919384-badb0274-5513-11e8-9872-f3b684ab2d6b.png">
Slik at vi unngår dette:
<img width="93" alt="screen shot 2018-05-11 at 12 12 16" src="https://user-images.githubusercontent.com/74510/39919660-9e734550-5514-11e8-9b5c-0a479464e71f.png">

Men på de minste størrelsene må vi nok øke tykkelsen litt ekstra for at den ikke skal bli for tyn. I utgangspunktet ser jeg ikke noe i veien for at vi beholder samme tykkelsene på denne nye spinnere som vi hadde fra før (kanskje litt tynnere på `XXL`- og `XXXL`-variantene), slik at vi egentlig bare endrer oppførsel/animasjon og farger. Hva tror du @sergiohaisch?

Jeg tror også Nicklas har rett ang. kontrast-verdier. Så det bør testes og muligens justeres litt.

2018-05-14 06:59 UTC, erlendev commented
Jeg syns heller vi skal bumpe major enn å tenke på å støtte gamle versjoner (være seg pga. størrelser eller andre ting). Gamle versjoner er støttet gjennom gamle versjoner av npm-modulen, hvorfor gjøre noe mer enn det?

2018-05-14 07:11 UTC, Lillebo commented
Det vil vel gjøre det enklere for prosjekter som allerede er i gang å adoptere den nye versjonen hvis vi støtter de samme størrelsene? Kan ikke se for meg at det vil innebære så fryktelig mye ekstra arbeid å inkludere dem i denne endringen?

2018-05-14 07:23 UTC, jcpgithub commented on packages/node_modules/nav-frontend-spinner-style/src/spinner-style.less
> +  .spinner-div-mixin(l, 40px, -7px, -9px, 13px);
jeg skal ta ny runde med en designer

2018-05-14 07:23 UTC, jcpgithub commented on packages/node_modules/nav-frontend-spinner-style/src/spinner-style.less
> +    border-color: #CCDEE6 transparent transparent transparent;
jeg skal ta ny runde med en designer

2018-05-14 09:03 UTC, erlendev commented
Trodde det her var snakk om å bevare support for de gamle, misforståelse fra min side.

2018-05-23 11:50 UTC, Lillebo commented
Erstattet av #282

2018-05-23 11:50 UTC, closed without merging