Role=alert på alertstripe:advarsel
navikt/aksel pull request #291
Opened 2018-05-30 07:45 UTC by JohRus

2018-05-30 10:50 UTC, Lillebo commented
Har snakket litt med @karinaldw og David, og vi er litt usikre på om dette er hensiktsmessig. Hva er bakgrunnen for dette endringsønsket?

2018-05-30 13:47 UTC, nutgaard requested changes

2018-05-30 13:47 UTC, nutgaard commented on package-lock.json
> +      "resolved": "http://a34apvl062.devillo.no:8082/repository/npm-all/@types/react-collapse/-/react-collapse-4.0.1.tgz",
Sitter du med en litt rar npm-config?

2018-05-30 13:47 UTC, nutgaard commented on packages/node_modules/nav-frontend-alertstriper/package.json
> +  "version": "1.0.13",
publiserings-jobben tar seg av bumping av versjon, så det bør ikke gjøres i PR

2018-05-31 07:18 UTC, JohRus commented
Alertstripen blir ikke lest opp når den rendres på skjermen. Role='alert' løste problemet.

@Lillebo

2018-05-31 09:49 UTC, Lillebo commented
Vi må teste litt hva funker best og komme tilbake til dette.

2018-05-31 11:11 UTC, nutgaard commented
> The following example uses role=alert which is equivalent to using aria-live=assertive.
https://www.w3.org/TR/WCAG20-TECHS/ARIA19.html

I tidligere løsninger har vi stortsett havnet på å legge til `aria-live: assertive`, `aria-atomic: true` og `role:alert` for at det skulle fungere best mulig i alle nettlesere/skjermlesere

2018-06-01 07:05 UTC, nutgaard approved these changes

2018-06-01 07:19 UTC, Lillebo commented
Fikk bl.a. dette innspillet fra @karinaldw:

>Because of its intrusive nature, the alert role must be used sparingly and only in situations where the user's immediate attention is required. Dynamic changes that are less urgent should use a less aggressive method, such as aria-live="polite" or other live region roles.

Ref. https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role

Forstod det på @deamondavid at han også var enig i at man bør være litt forsiktig med bruk av `role="alert"`.

Antar behovet for dette attributtet er litt avhengig av kontekst, og at det derfor kan være uheldig å ha det som default på absolutt alle instanser av advarsel-versjonen av Alertstripe. Lurer derfor på om vi ikke heller bør la konsumentene få ansvar for å bestemme om sitt tilfelle krever dette eller ikke, og evt. legge det til som en custom prop.

**Litt ved siden av, ang. `aria-live`**
Ble litt i tvil om det er så hensiktsmessig å ha `aria-live` på denne komponenten også. Jeg antar de fleste bruker den slik at den ikke rendres i det hele tatt før en eventuell feilmelding skulle oppstå? Får inntrykk av [docs](https://www.w3.org/TR/WCAG20-TECHS/ARIA19.html) at `aria-live` bør allerede ligge på siden fra starten av, for å definere en såkalt "live region" hvor dynamisk innhold *kan* oppstå. Ville det ikke derfor gi mer mening å ha `aria-live` på det kontainer-elementet hvor Alertstripe blir rendret i?

>Dynamically adding an element with an aria-live attribute or specialized role to the document also won't result in any announcement by assistive technologies (as, at that point, the browser/assistive technologies are not aware of the live region yet, so cannot monitor it for changes).

Ref: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions

2018-06-01 15:13 UTC, JohRus commented
Endret PR'en til å få `AlertStripeAdvarsel` til å akseptere en prop `role`.

2018-06-04 07:14 UTC, merged