:construction: wip
navikt/aksel pull request #3357
Opened 2024-11-12 14:03 UTC by JulianNymark

### Description

### Component Checklist 📝

- [ ] JSDoc
- [ ] Examples
- [ ] Documentation / Decision Records
- [ ] Storybook
- [ ] Style mappings (`@navikt/core/css/config/_mappings.js`)
- [ ] Component tokens (`@navikt/core/css/tokens.json`)
- [ ] CSS class deprecations (`@navikt/aksel-stylelint/src/deprecations.ts`)
- [ ] Exports (`@navikt/core/react/src/index.ts` and `@navikt/core/react/package.json`)
- [ ] New component? CSS import (`@navikt/core/css/index.css`)
- [ ] Breaking change? Update migration guide. Consider codemod.
- [ ] Changeset (Format: `<Component>: <gitmoji?> <Text>.` E.g. "Button: :sparkles: Add feature xyz.")

2024-11-21 10:24 UTC, JulianNymark commented
Right now it has a blue border on hover (even in error state) maybe it shouldn't be like this on error? 🤔 (though it's nice to have a hover indicator).

2024-11-21 15:14 UTC, KenAJoh commented on @navikt/core/css/darkside/form/index.css
> +@import "../date.darkside.css" layer(aksel.forms.components);
```suggestion
```
This PR solves it 🤞 
https://github.com/navikt/aksel/pull/3395

2024-11-21 15:14 UTC, KenAJoh commented on @navikt/core/css/darkside/date.darkside.css
> +  --axc-shadow-focus: 0 0 0 3px var(--ax-border-focus);
Think pretty much all focus-markings can be replaced with 
```
outline: 2px solid var(--ax-border-focus);
outline-offset: 2px;
```

Can then also refactor lots of the selectors that is not needed then anymore like 
```

// Don't need to check that its selected or disabled etc here
  .rdp-button:not(.rdp-day_selected, [disabled]):focus-visible,
  .navds-date__month-button:not(.rdp-day_selected, [disabled]):focus-visible {
    box-shadow: var(--axc-shadow-focus);
  }

// This is nit needed anymore
  .rdp-button.rdp-day_selected:not([disabled]):focus-visible,
  .navds-date__month-button.rdp-day_selected:not([disabled]):focus-visible {
    box-shadow:
      inset 0 0 0 1px var(--ax-bg-default),
      var(--axc-shadow-focus);
  }
```

2024-11-25 11:56 UTC, KenAJoh commented on @navikt/core/css/darkside/date.darkside.css
> +      outline: 2px solid var(--ax-border-focus);
```suggestion
      outline: 2px solid var(--ax-border-focus);
      outline-offset: -1px;
```

2024-11-25 11:56 UTC, KenAJoh commented on @navikt/core/css/darkside/date.darkside.css
> +      outline: 2px solid var(--ax-border-focus);
I think the `button` selector is to wildcardy since it targets native buttons used in caption to

2024-11-25 11:56 UTC, KenAJoh commented on @navikt/core/css/darkside/date.darkside.css
> +  .navds-date__caption__year,
```suggestion
```
These two elements are our selects and already get focus from select.css

2024-11-25 11:56 UTC, KenAJoh commented on @navikt/core/css/darkside/date.darkside.css
> +      outline-offset: 2px;
```suggestion
      outline-offset: 1px;
```

Think 1px offset looks better and avoids overlap
![Screenshot 2024-11-25 at 12 39 10](https://github.com/user-attachments/assets/77b85ebc-c1a5-45b1-bd22-41d1e4a8bca2)
![Screenshot 2024-11-25 at 12 39 25](https://github.com/user-attachments/assets/c45f8dd4-2f27-458d-b012-f1d23dfb3017)

2024-11-25 11:56 UTC, KenAJoh commented on @navikt/core/css/darkside/date.darkside.css
> +    box-shadow: inset 0 0 0 1px var(--ax-border-danger);
```suggestion
```
If you merge with main, this custom error code can be removed.

2024-11-25 11:56 UTC, KenAJoh commented on @navikt/core/css/darkside/date.darkside.css
>  .navds-date__popover:where(.navds-popover) {
This can be removed

2024-11-25 11:56 UTC, KenAJoh commented on @navikt/core/css/darkside/date.darkside.css
> +  .navds-date__modal& {
```suggestion
  .navds-date__modal & {
```

2024-11-25 11:56 UTC, KenAJoh commented on @navikt/core/css/darkside/date.darkside.css
> +      outline: 2px solid var(--ax-border-focus);
This target the monthpicker buttons differently than datepicker
![Screenshot 2024-11-25 at 12 55 41](https://github.com/user-attachments/assets/b56b7b61-8bcd-44fb-ba22-0cf4548b81ad)

2024-11-25 11:56 UTC, KenAJoh commented on @navikt/core/css/darkside/form/index.css
> +@import "../date.darkside.css";
Don't think this is needed anymore

2024-11-25 13:23 UTC, KenAJoh commented on @navikt/core/css/darkside/date.darkside.css
> +    box-shadow: 0 0 0 1px var(--ax-bg-accent-strong-pressed);
Sync this with Figma

2024-11-25 13:25 UTC, KenAJoh commented on @navikt/core/css/darkside/date.darkside.css
> +    color: var(--ax-text-default);
This currently breaks hover+active on caption-buttons
<img width="55" alt="Screenshot 2024-11-25 at 14 25 02" src="https://github.com/user-attachments/assets/fcc0f499-7898-49f4-bf62-894040c59eef">

2024-11-25 13:28 UTC, KenAJoh commented on @navikt/core/css/darkside/date.darkside.css
> +  .rdp-weeknumber.rdp-button:active {
Can this be replaced with our own small-button "seondary-neutral" here?

2024-11-25 13:29 UTC, KenAJoh commented on @navikt/core/css/darkside/date.darkside.css
> +    background: var(--ax-bg-accent-moderate-hover);
```suggestion
    background: var(--ax-bg-accent-moderate-hoverA);
```

2024-11-25 13:35 UTC, KenAJoh commented on @navikt/core/css/darkside/date.darkside.css
> +    text-decoration: line-through;
Today + disabled should have striketrough (currently underline)

2024-11-25 13:43 UTC, KenAJoh commented on @navikt/core/css/darkside/date.darkside.css
> +    text-decoration: underline;
Sync with figma-design. Might have to be a "::before"-psuedo-element now

2024-11-25 13:58 UTC, KenAJoh commented on @navikt/core/css/darkside/date.darkside.css
Update "middle" styling based on Figma 
![Screenshot 2024-11-25 at 14 58 09](https://github.com/user-attachments/assets/4bbb99f0-9824-45db-863e-7ec6422c6ea9)

2024-11-26 10:31 UTC, KenAJoh commented on @navikt/core/css/darkside/date.darkside.css
> +    text-decoration: line-through;
Ignore this

2024-11-29 12:41 UTC, KenAJoh requested changes

2024-11-29 12:41 UTC, KenAJoh commented on @navikt/core/css/darkside/date.darkside.css
> +  border-radius: var(--ax-border-radius-medium);
Both navds-date__caption__year and navds-date__caption__month have dobule borders now.

2024-11-29 12:41 UTC, KenAJoh commented on @navikt/core/css/darkside/date.darkside.css
All :disabled days have "active" state now indicating that they can be clicked.

2024-12-03 11:02 UTC, KenAJoh approved these changes
:shipit:

2024-12-03 11:09 UTC, merged