oppdater-veileder
navikt/aksel pull request #374
Opened 2018-08-24 06:43 UTC by orhels

* Gjør det mulig å angi posision på snakkeboblen. Gyldige verdier er 'flytende', 'topp', 'bunn', 'høyre' og 'venstre'.
* Fikser en prop-type feil

2018-08-24 10:26 UTC, thomasfl approved these changes

2018-08-24 10:28 UTC, thomasfl commented on development/app/components/App.js
>  export default class App extends Component {
Er det vanlig å legge inn endringer App.js i pull requester på nav-frontend-moduler?

2018-08-24 11:48 UTC, Lillebo requested changes
Veldig bra 👍 Dette er en såpass stor endring at jeg tror vi bør bumpe major i `package.json` også.

2018-08-24 11:48 UTC, Lillebo commented on development/app/components/App.js
>  export default class App extends Component {
Nei, denne fila må ut av PRen 🙂

2018-08-27 08:08 UTC, Lillebo approved these changes

2018-08-27 08:09 UTC, merged