Endre textarea props til å extende TextareaHTMLAttributes
navikt/aksel pull request #412
Opened 2018-12-14 14:08 UTC by frederikgdl

For #411 
Dette fungerer hos meg. Vil dere ha finere kontroll over props?

2018-12-14 14:21 UTC, frederikgdl commented
Noe problem ved å ikke passe value fra TextareaControlled videre til Textarea?

2018-12-19 14:54 UTC, thomasfl approved these changes

2019-01-10 06:49 UTC, Lillebo requested changes
Takk for PR 🙂

2019-01-10 06:49 UTC, Lillebo commented on packages/node_modules/nav-frontend-skjema/src/textarea-controlled.tsx
> +        const { defaultValue, value, ...other } = this.props;
Hm, tror ikke du trenger å hente ut `value` her hvis du endrer rekkefølgen på props i render til dette:
```
return <Textarea
    onChange={this.onChange}
    {...other}
    value={this.state.text} />;
```
Så slipper vi å definere en const vi ikke bruker.

2019-01-10 08:17 UTC, Lillebo approved these changes

2019-01-10 08:22 UTC, frederikgdl commented on packages/node_modules/nav-frontend-skjema/src/textarea-controlled.tsx
> +        const { defaultValue, value, ...other } = this.props;
Lurt!

2019-01-10 08:23 UTC, merged