Legger til 'tabPanel' prop på Panel-komponent
navikt/aksel pull request #422
Opened 2019-01-11 08:20 UTC by Lillebo

Hvis komponenten skal brukes i kombinasjon med Tabs-komponenten kan denne propen brukes for å gi panelet en passende styling. Tidligere var man nødt til å manuelt sette `border-top: 0; border-top-left-radius: 0; border-top-right-radius: 0;`.

<img width="742" alt="screenshot 2019-01-11 at 09 18 56" src="https://user-images.githubusercontent.com/74510/51021533-1db76200-1582-11e9-8d11-8799f4990d4d.png">

2019-01-21 14:15 UTC, erlendev requested changes
Jeg er ikke helt tilhenger av denne typen endringer av `Panel`. `Panel`-komponenten bør etter min mening holdes så clean som mulig, fordi den brukes i mange forskjellige settinger, og om vi tilpasser den til forskjellige use-cases med forskjellige komponenter som er bygd på den, vil den bli vanskeligere å bruke jo flere tilpasninger vi lager.

Foreslår at vi heller lager en egen komponent, f.eks. `<TabPanel />`, som bruker både Panel og Tabs, for dette use-caset.

2019-01-22 09:12 UTC, Lillebo commented
Jau, deler bekymringen din 👍Litt usikker på hvordan vi ellers kan gjøre dagens bruk litt enklere:
<img width="742" alt="screenshot 2019-01-22 at 10 08 59" src="https://user-images.githubusercontent.com/74510/51524294-0d2ea380-1e2e-11e9-9d6b-83653483ce66.png">

Hvordan tenker du en evt. `<TabPanel />` skal bruke Tabs? Eller tenker du at den bare skal være en wrapper for `Panel`, og at man f.eks. importerer via `import { TabPanel } from 'nav-frontend-paneler'`?

2019-01-23 14:47 UTC, erlendev commented
Går utifra at tanken her er at contentet i panelet skal endre seg når man skifter tabs? 

Jeg tenker ihvertfall at dette bør være en egen modul, på lik linje med de andre avartene vi har av paneler idag (slik som `Ekspanderbartpanel` og `Lenkepanel`), f.eks. `nav-frontend-tabpanel`.

Litt usikker på hva som er beste fremgangsmåte. [TabProps](https://github.com/navikt/nav-frontend-moduler/blob/fb7a5ab4cc772eb5f25328e348c9ed9b06a54961/packages/node_modules/nav-frontend-tabs/src/tab.tsx#L11) kan kanskje extendes til å ha en property for å si noe om hva som rendres som `children` i `Panel`. Da må vi muligens inn med noe state for å holde styr på aktiv tab, men det er en mulig løsning.

2019-01-23 15:06 UTC, Lillebo commented
I utgangspunktet hadde jeg ikke tenkt å gjøre noe mer enn å forenkle stylingen av paneler som skal kombineres med Tabs. Per i dag må jo switching av innhold avhengig av aktiv tab håndteres manuelt som en reaksjon på `onChange`.

Men vi kan godt vurdere om vi heller lager en ny komponent som fikser begge deler. I så fall blir nok dette en litt større jobb, men sikkert også en ryddigere måte å løse det på 👍

2019-02-20 12:23 UTC, Lillebo commented
Utgår i påvente av en mer omfattende `TabPanel` komponent.

2019-02-20 12:23 UTC, closed without merging