Fikser en del kontrast issues, oppdaterer lenke-styling
navikt/aksel pull request #424
Opened 2019-01-17 09:29 UTC by Lillebo

![contrast](https://user-images.githubusercontent.com/74510/51307118-2d7ded00-1a3f-11e9-9167-cfc8d74230d9.png)
![link-style](https://user-images.githubusercontent.com/74510/51307119-2d7ded00-1a3f-11e9-9361-a4168ae5cd4c.png)

2019-01-21 14:00 UTC, erlendev requested changes

2019-01-21 14:00 UTC, erlendev commented on packages/node_modules/nav-frontend-ekspanderbartpanel-style/src/index.less
> +  border-radius: 4px;
Denne burde vel angis i `rem`?

2019-01-21 14:00 UTC, erlendev commented on packages/node_modules/nav-frontend-ekspanderbartpanel-style/src/index.less
> +      cursor: default;
Trenger vi å legge føringer på cursor-styling i et åpent panel? Content'et er jo bestemt av de som bruker panelet, sånn jeg ser det. Og om noe, kan vi kanskje begrense oss til å sette `cursor: pointer;`  på `.ekspanderbartPanel__hode`?

2019-01-21 14:00 UTC, erlendev commented on packages/node_modules/nav-frontend-skjema-style/src/input-panel.less
> +  border-radius: 4px;
Burde kanskje også bruke `rem`?

2019-01-21 14:17 UTC, Lillebo commented on packages/node_modules/nav-frontend-ekspanderbartpanel-style/src/index.less
> +  border-radius: 4px;
Ble egentlig litt usikker på dette. Kan tenke meg vi omsider kommer til å vurdere å bumpe `rem` fra 16 til 18 relativt snart, og jeg er ikke så sikker på om det er ønskelig at ting som border-tykkelse, -radius, paddings osv. bør bli påvirket av det.

Ser det er blitt gjort litt forskjellig på slike stiler flere steder i koden vår: `rem` enkelte steder og `px` andre steder. Lurer på om jeg faktisk foretrekker `px` her 🤔

2019-01-22 11:49 UTC, Lillebo commented on packages/node_modules/nav-frontend-ekspanderbartpanel-style/src/index.less
> +  border-radius: 4px;
Vi kan heller ta en gjennomgang av dette når bumping av `rem` eventuelt blir aktuelt. Fikser til `rem` inntil videre 👍

2019-01-23 14:49 UTC, erlendev approved these changes

2019-01-23 15:06 UTC, merged