Legg til mulighet for å overstyre tag som brukes for tittel i Ekspanderbartpanel
navikt/aksel pull request #428
Opened 2019-01-25 10:14 UTC by stephenramthun

Savner muligheten til å bestemme tag for tittel. Motivasjonen for dette er at vi i teamet har en applikasjon som bruker Ekspanderbartpanel-komponenter som seksjoner på en side, hvor hver tittel fungerer som seksjonsoverskrifter. Det vil da være riktig med tanke på UU å ordne titlene i et overskriftshierarki, h1-h6.

Har lagt til en property "tag" til Ekspanderbartpanel. Den er optional for å bevare bakoverkompatibilitet.

2019-01-25 11:03 UTC, Lillebo requested changes
Hm, jeg tror dette allerede kan gjøres ved å bruke `EkspanderbartpanelBase` og så angi custom tittel-markup via `heading`-propen:

```
import { EkspanderbartpanelBase } from 'nav-frontend-ekspanderbartpanel'

<EkspanderbartpanelBase heading={<h2 className="ekspanderbartPanel__heading">Klikk her for å åpne/lukke panelet</h2>} border>
    Panelet vil da ekspandere og vise innholdet.
</EkspanderbartpanelBase>
```

Samtidig ser jeg egentlig ikke noe problem med å legge til en `tag` prop. Har du noen tanker @erlendev?

2019-02-27 08:55 UTC, erlendev commented
Beklager sent svar.

Jeg syns denne endringen er helt fin @Lillebo. `EkspanderbartpanelBase` sin `heading` property tenker jeg er til for litt mer kompliserte behov enn å endre på `tag`, og den trenger sånn sett ikke være noen hindring for å legge til konfigurasjonsmuligheter på `Ekspanderbartpanel`.

2019-02-27 08:56 UTC, erlendev approved these changes

2019-02-27 09:09 UTC, Lillebo approved these changes

2019-02-27 09:09 UTC, merged