Normalisering av skjemastyling
navikt/aksel pull request #43
Opened 2017-08-07 09:50 UTC by nutgaard

Tittet på mulig løsning for #42 

Oppdaget noen smågreier med stylingen som var der fra før av, så oppretter egne issues på det.

2017-08-07 12:15 UTC, erlendev requested changes
Trenger vi å gjøre !!feil for å sjekke truthiness til classNames()? Er classNames() avhengig av bool? Litt kjipt for lesbarheten i komponentene.

2017-08-07 12:27 UTC, erlendev commented on packages/node_modules/nav-frontend-skjema-style/src/input.less
> +  background-color: transparent;
Hvorfor skal background-color settes til transparent? Vil den ikke da få background-color:blue på en f.eks. en div som har blå bakgrunnsfarge da?

2017-08-07 12:43 UTC, nutgaard commented on packages/node_modules/nav-frontend-skjema-style/src/input.less
> +  background-color: transparent;
Er styling flyttet fra `select.less`, men godt spørsmål. 
Tror vi nokså greit kan sette `@white` istedet der.

2017-08-23 10:40 UTC, nutgaard commented
Fjernet `!!` fra de stedene jeg fant det, og byttet fra `transparent` til `@white`.

2017-08-23 11:15 UTC, erlendev approved these changes

2017-08-23 13:31 UTC, merged