Fjerner deafult maks lengde for text area.
navikt/aksel pull request #490
Opened 2019-05-23 11:51 UTC by hakonph

2019-05-24 08:42 UTC, Lillebo requested changes
Takk for PR 🙂Se kommentarer.

2019-05-24 08:42 UTC, Lillebo commented on packages/node_modules/nav-frontend-skjema/src/textarea.tsx
> +        maxLength: undefined,
Tenker kanskje denne defaulten bare kan fortsette å være `2000`. Og så endrer vi bare kommentaren til `maxLength` i interface til: 

> Maks antall tegn som kan skrives inn i tekstområdet. Angi `0` for å skru av tegn-begrensningen. Default er `2000`.

Da slipper de som allerede bruker denne komponenten å oppdatere noe. Retter du opp og legger til et eksempel med bruk av `maxLength={0}` for å skru av tegnbegrensning i `*.overview.mdx`-fila?

Tror også vi bør fikse slik at `<p className="textarea--medMeta__teller">`-elementet på [linje 184](https://github.com/navikt/nav-frontend-moduler/blob/2b040a94cf65bf413d4e5886b40539b9a2c51660/packages/node_modules/nav-frontend-skjema/src/textarea.tsx#L184) blir fjernet om bruker vil skru av tegnbegrensningen.

2019-05-24 08:42 UTC, Lillebo commented on packages/node_modules/nav-frontend-skjema/md/textarea/Textarea.overview.mdx
> +    <TextareaControlled label="Textarea-label" feil={{feilmelding: 'Her er det noe feil.'}} />
Flott at du fikser dette kode-eksempelet 👍 Du kan fjerne bruk av `<Example>` her.

2019-05-24 08:42 UTC, Lillebo commented on CONTRIBUTING.md
> +Støter **IKKE** siste verson av node, bruk node LTS verson 10.
Ble fikset med #492, denne setningen kan fjernes.

2019-05-24 08:42 UTC, Lillebo commented on CONTRIBUTING.md
> +Dette bygger **ikke** automatisk endringene på typskript komponentene.
Denne setningen kan fjernes da dette er beskrevet her: https://github.com/navikt/nav-frontend-moduler/blob/master/CONTRIBUTING.md#bruk-av-typescript

2019-05-27 06:43 UTC, hakonph commented on CONTRIBUTING.md
> +Dette bygger **ikke** automatisk endringene på typskript komponentene.
Kan fjerne den, men føler den burde være her da nesten alle komponentene er typscript.
Godt mulig den burde ha en annen formulering

2019-05-28 08:44 UTC, Lillebo requested changes

2019-05-28 08:44 UTC, Lillebo commented on packages/node_modules/nav-frontend-skjema/src/textarea.tsx
> +                    <Teller antallTegn={antallTegn} maxLength={maxLength} tellerTekst={tellerTekst}/>
Tror jeg hadde foretrukket om denne ble endret til `{maxLength && <Teller ... />}`. Synes det da blir litt enklere å lese at telleren uteblir om `maxLength` er `falsy/zero`. Da kan du også fjerne if-setningen på linje 204.

2019-05-28 08:44 UTC, Lillebo commented on CONTRIBUTING.md
> +Dette bygger **ikke** automatisk endringene på typskript komponentene.
Ja, vi burde sikkert nevne dette tidligere/tydeligere 👍 Kan prøve å fikse det i en annen update senere. Men fint om du fjerner her inntil videre.

2019-05-29 07:23 UTC, hakonph commented on CONTRIBUTING.md
> +Dette bygger **ikke** automatisk endringene på typskript komponentene.
Mener fortsatt det burde stå her, men har fjernet det

2019-05-29 08:39 UTC, Lillebo approved these changes

2019-05-29 08:39 UTC, merged