Tabell komponent
navikt/aksel pull request #542
Opened 2019-09-06 13:52 UTC by thomasfl

Tabellkomponent som produserer standard html table element og responsiv css med flex.

![image](https://user-images.githubusercontent.com/1520/64433126-2551eb00-d0be-11e9-89f3-fd7ffe7710d1.png)

Issues:
 - Brekkpunktet for mobilvisning er hardkodet til 640px. For små tabeller med få kolonner, så trenger man ikke egen mobilvisning.

2019-09-09 09:37 UTC, Lillebo requested changes
Takk for PR 🙂Det bør kanskje nevnes at vi allerede er i gang med en tabell-komponent (#309) som kan forhåndsvises her: http://archivedworks.com/dev/nav/table/

I første omgang er dette tenkt som en ren style-pakke - uten noe JS-komponenter. Men for å vise rene style-pakker på design.nav.no så må vi skrive om en del logikk på hvordan komponentene listes opp der - som dessverre har ført til at denne style-pakken har latt vente på seg en stund.

Sliter litt med å se hva JS-komponentene i denne PRen egentlig gjør for noe utover å tegne opp standard `<table>`-markup 🤔 Hva gjør `adjustChildrenWidths`-funksjonen f.eks.?

2019-09-09 12:11 UTC, thomasfl commented
@Lillebo Jeg visste ikke at det var en annen tabellkomponent under utvikling. Funksjonen `adjustChildrenWidths` beregner relative kolonnebredder. `<NavTable columnWidths={[1,1,3]}>` blir til 3 kolonner med 20%, 20% og 60% bredder. Context API'et til React brukes for at alle cellene skal vite hvor brede de skal være.

2019-09-11 08:46 UTC, Lillebo commented
Ja, ser du fikk litt annen informasjon på Slack - beklager det. Vil gjerne unngå at arbeidet som allerede er lagt ned i den tabell-stil-pakken går tapt, så tenker nok at vi går for den i første omgang.

Føler egentlig det er litt unødvendig med noe Javascript-komponent her. Om noen trenger JS-kontrollerte tabeller så finnes det mange gode biblioteker å velge mellom der ute (med sortering, paginering, filtrering osv) - og da det er kanskje enklest om vi bare tilbyr styling slik at folk står mer fri til å velge det som passer best til deres behov.

Tenker også det er vanskelig å finne noe god universell løsning på responsivitet for slike tabeller. Tror kanskje det er noe som helst bør overlates til konsumentene.

2019-09-11 09:07 UTC, thomasfl commented
Du har kommet mye lenger enn meg i tabeller, så jeg lukker denne pull requesten.

Responsive tabeller, betyr oftest at tabellene må kunne vises som tabeller med bare 1 kolonne på små skjermer, samtidig som det er en fordel å alltid rendre table, tr og td tagger.

Neste gang jeg lager en pull request til nav-frontend-moduler, så venter jeg til jeg får svar fra deg først.

2019-09-11 09:31 UTC, Lillebo commented
Høres bra ut, og beklager igjen for at du fikk litt feil beskjed 🙂

2019-09-11 09:31 UTC, closed without merging