Fikse støtte for ikoner i Lenke #568
navikt/aksel pull request #579
Opened 2019-10-18 11:14 UTC by unorsk

Legger til støtte fot svg-ikoner #568

2019-10-18 11:42 UTC, Lillebo requested changes
Se kommentarer 🙂

2019-10-18 11:42 UTC, Lillebo commented on packages/node_modules/nav-frontend-lenker-style/src/lenker-mixins.less
> +    width: 1rem;
Hm, burde størrelsene for ikonet være definert med `em` i stedet for `rem` her? Tenker det kan være fint om dette skalerer med font-størrelsen 🤔

Hvordan vil f.eks. dette funke:

```jsx
<Undertittel>
    <Lenke href="#">
        <span>lenke med ikon</span>
        <SvgLinkIcon />
    </Lenke>
</Undertittel>
```

2019-10-18 11:42 UTC, Lillebo commented on packages/node_modules/nav-frontend-lenker-style/src/lenker-mixins.less
> +    margin-left: 0.5rem;
Samme her med `em` i stedet for `rem`?

2019-10-18 11:42 UTC, Lillebo commented on packages/node_modules/nav-frontend-lenker/_lenke.example.js
>  import PT from 'prop-types';
Hm, tror faktisk ikke denne filen brukes til noe 🤔 Kan sikkert bare slettes.

2019-10-18 11:42 UTC, Lillebo commented on packages/node_modules/nav-frontend-lenker/_lenke.example.js
> +const SvgLinkIcon = () => (<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><g stroke="#000" strokeLinecap="round" strokeLinejoin="round" strokeMiterlimit="10" fill=
Denne kan bare flyttes ut til `Lenke.overview.mdx`. Den bør sikkert være med i kode-eksempelet også, bare for å vise folk at den kun inneholder SVG-kode - slik vi gjør her med `<Cog />`: https://design.nav.no/components/knapp#plassering-av-ikon

2019-10-18 11:42 UTC, Lillebo commented on packages/node_modules/nav-frontend-lenker/md/Lenke.overview.mdx
> +    Dette er en <Lenke href="#"><span>lenke med ikon</span><SvgLinkIcon /></Lenke>
Legger du til eksempler med ikon både forran og bak? Og kanskje et eksempel med at ikonet skalerer med font-størrelse når du får fikset det også?

2019-10-21 08:29 UTC, unorsk commented on packages/node_modules/nav-frontend-lenker/md/Lenke.overview.mdx
> +    Dette er en <Lenke href="#"><span>lenke med ikon</span><SvgLinkIcon /></Lenke>
ja, det er gjort

2019-10-21 08:30 UTC, unorsk commented on packages/node_modules/nav-frontend-lenker-style/src/lenker-mixins.less
> +    margin-left: 0.5rem;
done

2019-10-21 08:52 UTC, Lillebo commented on packages/node_modules/nav-frontend-lenker/md/Lenke.overview.mdx
> +## Lenke i tittel
Kanskje denne overskriften bare kan erstattes med vanlig brødtekst: "Ikoner inne i lenker vil skalere med tekst-størrelsen."

Eksempelet nedenfor hører på en måte fortsatt til den forrige overskriften 🤔

2019-10-21 13:10 UTC, unorsk commented on packages/node_modules/nav-frontend-lenker/md/Lenke.overview.mdx
> +## Lenke i tittel
Oppdatert

2019-10-21 13:19 UTC, Lillebo approved these changes

2019-10-21 13:27 UTC, merged