Endrer hidden fra å fjerne textarea til å fjerne hele komponenten
navikt/aksel pull request #581
Opened 2019-10-21 07:56 UTC by hakonph

Sån som denen er satt opp dag fjerner hidden selve teksareat
mens skjema feilmeldingen og labelen forblir synlig

2019-10-21 08:29 UTC, Lillebo requested changes
Har tenkt litt på dette siden den forrige pull requesten din hvor [du nevnte det samme](https://github.com/navikt/nav-frontend-moduler/pull/575#issuecomment-543114996).

Jeg er litt usikker på om det er så ønskelig å introdusere dette mønsteret i komponentene våre. Jeg føler dette rokker for mye både med hvordan standard HTML fungerer, og hvordan React-komponenter generelt fungerer. I standard HTML så vil f.eks. ikke et element bli fjernet fra DOMen hvis det får et `hidden`-attributt. Og med denne endringen så vil heller ikke React sine lifecycle-metoder rundt mounting/unmounting trigge i takt med hva som ligger i DOM til enhver tid.

2019-10-21 08:37 UTC, Lillebo commented
Om man ønsker å fjerne komponenter fullstendig så bør det håndteres på et høyere nivå enn som en prop/attributt på selve komponenten:

```jsx
if (visTextarea) {
    return <Textarea />;
}
```

Ikke:
```jsx
<Textarea hidden />
```

2019-10-21 09:02 UTC, hakonph commented
denne har allerede støtte for hidden som prop men den oppfører seg veldig rart.
skuler textarea men ikke feilmeldingen og labelen

Føler det er mye mer the react way og skrive
```tsx
<Textarea hidden={!vistekstarea} />
```

enn 
```tsx
{vistekstarea && <Textarea />}
```
føler også dette er nødvendig for nesten alle og kunne bruke hidden.
det blir til at det første vi gjør når vi bruker frontendkomponentene er og importere dem og legge til hidden.

Man burde i alle fall enten fjerne hidden fra Ts prop eller gjøre noe fornuftig med den

2020-02-04 08:23 UTC, Lillebo commented
Lukker denne.

Foretrukket løsning på dette behovet er å heller la komponenten videreformidle slike HTML-attributter til elementene internt i komponenten. Da slipper vi å etablere noen ulik oppførsel for slike attributter når de settes på en React-komponent vs. et vanlig HTML-element.

F.eks. så støtter Textarea-komponenten vår nå de samme attributtene som et standard `<textarea />` element. Og effekten av å sette `hidden`-attributtet på React-komponenten (`<Textarea hidden />`) vil være identisk til om man heller setter dette attributtet på et vanlig HTML-element (`<textarea hidden />`).

Det vil vel og merke kunne oppstå noe knot ved at enkelte av komponentene våre ikke sprer slike attributter på sitt ytterste HTML-element (som `Textarea`-komponenten som wrappes i flere `<div>`-elementer f.eks.). Men dette kan uansett løses relativt enkelt ved å heller wrappe komponenten i et eget HTML-element som man da i stedet gir `hidden`:

```jsx
<div hidden>
    <Textarea />
</div>
```

Uansett, hvis behovet heller er å enkelt kunne vise/skjule en komponenten så holder jeg fast ved at dette er noe som bør håndteres i logikken der komponenten brukes - og ikke internt i den enkelte komponent - àla:

```jsx
if (visTextarea) {
    return <Textarea />;
}
```

2020-02-04 08:23 UTC, closed without merging