Update LICENSE
navikt/aksel pull request #619
Opened 2019-11-20 15:59 UTC by erlendev

Ser ut som streamline-license URLen ikke fungerer (gir bare 401 på medium.com). Oppdaterte med url til extended-license.html, tipper det er den man skal bruke? Ellers er det også en Standard License agreement her https://pages.streamlineicons.com/standard-license, litt usikker på hvilken man har lenket til, men går utifra at man har extended i NAV.

2019-11-21 13:46 UTC, nutgaard requested changes
@sergiohaisch @Lillebo
En av dere som vet hvilken lisens det er prat om?

2019-11-22 12:59 UTC, Lillebo submitted a review, later dismissed
Har en kvittering her som bekrefter at det er extended-lisens vi har 👍

2019-11-25 11:59 UTC, Lillebo commented
La inn oppdatert tekst om MIT-lisensen samtidig, som angitt her: https://github.com/navikt/offentlig/blob/master/LISENSIERING.md#lisensiering-av-nav-sine-kodebaser

2019-11-29 09:56 UTC, Lillebo approved these changes

2019-11-29 09:56 UTC, merged