Lenkepanel som kan brukes med egendefinert innhold.
navikt/aksel pull request #62
Opened 2017-08-23 11:41 UTC by kjarbr

For å ta vare på funksjonaliteten må vi lage et nytt lenkepanel som kun tar inn tekst.

2017-08-23 12:07 UTC, nutgaard commented
Føler vi bør ta det "nye lenkepanelet" i samme slengen her, slik at det ikke blir ett tidsrom der vi har "mistet" funksjonalitet. Det nye kan jo også bruke denne komponenten. :)

2017-08-30 07:12 UTC, nutgaard requested changes
Føler vi bør ta det "nye lenkepanelet" i samme slengen her, slik at det ikke blir ett tidsrom der vi har "mistet" funksjonalitet. Det nye kan jo også bruke denne komponenten. :)

2017-09-06 08:47 UTC, kjarbr commented
Det nye panelet bør vel hete LenkePanel, og det nye f.eks LenkeInnholdsPanel? 
Så hvordan forandrer man navnet på en modul?


> 30. aug. 2017 kl. 09.12 skrev Nicklas Utgaard <notifications@github.com <mailto:notifications@github.com>>:
> 
> @nutgaard requested changes on this pull request.
> 
> Føler vi bør ta det "nye lenkepanelet" i samme slengen her, slik at det ikke blir ett tidsrom der vi har "mistet" funksjonalitet. Det nye kan jo også bruke denne komponenten. :)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/navikt/nav-frontend-moduler/pull/62#pullrequestreview-59462810>, or mute the thread <https://github.com/notifications/unsubscribe-auth/ABYkEJv6MNHX5C79I5Rf1WrhKsaNg5XFks5sdQtVgaJpZM4O_4g_>.
>

2017-09-06 08:49 UTC, kjarbr commented
Det gamle panelet bør få det nye navnet…

> 30. aug. 2017 kl. 09.12 skrev Nicklas Utgaard <notifications@github.com>:
> 
> @nutgaard requested changes on this pull request.
> 
> Føler vi bør ta det "nye lenkepanelet" i samme slengen her, slik at det ikke blir ett tidsrom der vi har "mistet" funksjonalitet. Det nye kan jo også bruke denne komponenten. :)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/navikt/nav-frontend-moduler/pull/62#pullrequestreview-59462810>, or mute the thread <https://github.com/notifications/unsubscribe-auth/ABYkEJv6MNHX5C79I5Rf1WrhKsaNg5XFks5sdQtVgaJpZM4O_4g_>.
>

2017-09-13 07:26 UTC, nutgaard commented
Anbefaler å flytte alt inn i samme modul.

2017-11-14 12:12 UTC, erlendev commented
Er dette en duplikat av #137?

2017-11-15 08:52 UTC, closed without merging