bakgrunnsfarge som prop i snakkeboble
navikt/aksel pull request #638
Opened 2020-01-15 08:39 UTC by andersnav

Vi går over fra å bruke egne komponenter til nav-frontend, og trenger da å kunne angi bakgrunnsfarge på snakkebobla

2020-01-15 08:48 UTC, Lillebo requested changes
Hm, trenger dette å være en egen prop? 🤔 Hvorfor ikke bare:

```tsx
<Snakkeboble style={{ background: '#FFF2E0' }} />
```

Ser at komponenten ikke støtter det der ☝️per nå, men tar gjerne imot en PR som endrer slik at `SnakkebobleProps` utvider `HTMLAttributes<HTMLDivElement>`, og at komponenten sprer øvrige props på det ytterste elementet 🙂

2020-01-15 08:53 UTC, Lillebo commented
Ser ut som det er lenge siden denne komponenten ble jobbet med. Hadde vært fint om den ble utbedret til å støtte en custom `className` prop også når vi først ser på den 😀

2020-01-15 14:07 UTC, andersnav commented
@Lillebo, jeg endret den til å bare ta inn className, så legger vi heller til css på vår side. Ville initielt ikke gjøre det pga trøbbel med css modules, men fikk det å funke

2020-01-16 08:58 UTC, Lillebo approved these changes
Knallbra 👍

2020-01-16 08:58 UTC, merged