Add description-prop for input elements
navikt/aksel pull request #666
Opened 2020-02-16 17:22 UTC by frodehansen2

Legger til optional description prop for fieldset of inputs. Gir mulighet for å legge til innhold mellom label/legend og innhold.

2020-02-17 09:11 UTC, Lillebo requested changes
Veldig bra 👍 Men tror kanskje vi burde wrappe denne i en div for å sikre gjennomførte avstander til elementene rundt ja 🤔

Tenker kanskje `margin-bottom` på `0.5rem` for `.skjemaelement__description`, og `1rem` på `.skjemagruppe__description` (med unntak for `CheckboxGruppe` og `RadioGruppe`) - eller noe sånt?

Og så bør vi nok oppdatere dokumentasjonen med eksempler på dette også.

2020-02-17 09:14 UTC, Lillebo commented
Resolves #650

2020-02-17 14:05 UTC, Lillebo commented
La inn en liten visuell justering på `skjemaelement__description` med en `margin-top:-0.25rem` for å fikse dette:

<img width="732" alt="Screenshot 2020-02-17 at 15 03 32" src="https://user-images.githubusercontent.com/74510/74660596-b01f3180-5196-11ea-85b6-eb849b1aebf2.png">

Og justerte litt på ordlyden i docs. Da er denne egentlig good-to-go imo 👍 Men bør ta en liten avsjekk med resten av teamet før vi merger inn.

2020-02-18 09:31 UTC, frodehansen2 commented
Supert. Er det lenge til den evt. merges inn?

2020-02-20 11:28 UTC, Lillebo approved these changes

2020-02-20 11:33 UTC, merged