Oppfordre til å ikke bruke placeholders i skjema-elementer
navikt/aksel pull request #712
Opened 2020-04-20 14:09 UTC by KenAJoh

Closes #695 
Ønskes feedback på bruk av språk. Oppfordrer/anbefaler/ønsker osv

2020-04-21 11:08 UTC, Lillebo requested changes
Veldig bra 👍 Skjønner hva du har tenkt med å la hoved-teksten bo under SkjemaGruppe, men tror kanskje ikke det er helt riktig sted for den å bo. SkjemaGruppe er en ganske spesifikk `fieldset`-komponent, og ikke en overordnet wrapper/konteiner for alle skjema-relaterte ting.

Hva tenker du om å la denne teksten få sin egen side under [Tilgjengelighet](https://design.nav.no/accessibility) - litt på samme måte som vi gjør med alt-tekster?

2020-04-21 11:26 UTC, KenAJoh commented
> Hva tenker du om å la denne teksten få sin egen side under [Tilgjengelighet](https://design.nav.no/accessibility) - litt på samme måte som vi gjør med alt-tekster?

Tenker det er en kjempegod ide! Kan da skrive litt mer utfyllende forklaring og generere noen eksempler som viser hvorfor placeholders er frarådet, samt gode alternativ.

2020-04-21 11:29 UTC, Lillebo commented
Knall 🙂

2020-04-27 11:51 UTC, Lillebo approved these changes

2020-04-28 07:37 UTC, merged