Update other.json
navikt/aksel pull request #721
Opened 2020-05-04 06:14 UTC by NunoCardoso

2020-05-04 06:57 UTC, nutgaard commented on guideline-app/app/data/components/other.json
> +    "repository": "https://navikt.github.io/eessi-pensjon-ui",
Burde vel være `https://github.com/navikt/eessi-pensjon-ui` ?

2020-05-05 10:24 UTC, NunoCardoso commented
Jeg skal også eksportere FileUpload til en egen js-fil, jeg jobber fortsatt med å gjøre den tynnere

2020-05-12 06:08 UTC, nutgaard commented
Er det en vei å bruke den komponenten uten å innstallere hele eessi-pensjon-ui? Ser ut til at det prosjektet er litt alt eller ingenting? Isåfall tenker at vi heller burde se på å få implementere tilsvarende komponent i nav-frontend eller som standalone-komponent.

2020-05-13 09:37 UTC, NunoCardoso commented
> Er det en vei å bruke den komponenten uten å innstallere hele eessi-pensjon-ui? Ser ut til at det prosjektet er litt alt eller ingenting? Isåfall tenker at vi heller burde se på å få implementere tilsvarende komponent i nav-frontend eller som standalone-komponent.

Mmm ja, repoen er ikke liten. Man kan importere bare:

 `import FileUpload from 'eessi-pensjon-ui/dist/FileUpload'`

Jeg prøvde det på et annet prosjekt, og `npm ls` viser at det bare importerer avhengighet til FileUpload, ikke for alle eessi-pensjon-ui komponenter.

Likevel kan jeg lage separate repos for noen av disse komponentene hvis du synes det er verdt det. Jeg kan begynne og prøve det med FileUpload

2020-05-13 10:48 UTC, nutgaard commented
Svaret på spørsmålet er vel da egentlig "nei"? :P For må vel innstallere hele `eessi-pensjon-ui` for å bruke den importen der. 

Hmm.. Mulig jeg husker feil, men er ikke `npm ls` bare en kommando for å liste opp innstallerte pakker og hvordan de henger sammen? Så hvordan man evt bruker de i ettertid vil vel ikke påvirke output derifra. Må evt bruke noe alà `webpack-bunle-analyzer` for å titte på hva som blir tatt med når man bygger, men vil tro at de fleste bygge-pipelines bare tar med det de trenger.

Men det var en liten avsporing. :) 
Jeg er nok av den oppfatningen av det bør lages ett selvstendig repo uten avhengigheter til `eessi-pensjon-ui` eller evt lages som en modul i nav-frontend. 
Hovedprinsippet bak det er at eessi-pensjon-ui er ett prosjekt-spesifikt bibliotek og bør derfor ikke deles utover prosjektet det er laget for. 

Om/Når man ønsker å dele komponenter på tvers av prosjekter så bør disse i all hovedsak plasseres i nav-frontend. Men i visse tilfeller ser vi at det ikke er super-gunstig pga størrelsen/kompleksiteten av komponenten og da kan det deles via via `other.json`. De komponentene som deles der bør da være frikoblet fra en eventuell prosjekt-opprinnelse.

^^ 
Er bare min mening på saken, gitt sånn jeg har forstått formålet med nav-frontend. Mulig @Lillebo eller noen andre fra designsystemet-teamet har bedre innsikt i hvordan dette er tiltenkt å fungere?

2020-05-13 11:37 UTC, Lillebo commented
Enig med @nutgaard 👍Tanken bak `other.json` var jo å være et lavterskel-tilbud for deling av alt mulig rart, men det hadde vært uheldig om konsumentene ble nødt til å installere et helt prosjekt for å bruke en enkelt komponent.

FileUpload bør nok skilles ut som en selvstendig NPM-modul før den kan deles på tvers.

2020-05-14 10:05 UTC, NunoCardoso commented
Ok, da kan jeg opprett nav-frontend-filopplasting repoen?

2020-05-14 10:17 UTC, Lillebo commented
Jeg ville kanskje unngått å bruke noe "nav-frontend"-prefix/navngiving da det lett kan misforstås som at denne filopplastingen er en del av nav-frontend-moduler.

Kanskje du kan gjøre noe ala dette: https://github.com/navikt/datovelger

2020-05-20 10:06 UTC, NunoCardoso commented
@nutgaard Filopplasting er nå i sin egen repo.

2020-05-20 10:34 UTC, nutgaard commented
Helt supert. 👍

Har bare to anbefalinger;
1. publiser det til npmjs. Med git-repo-avhengigheter så må hele repoet klones, så man får mye mer enn man egentlig trenger. Og git-tags kan endres på, så hele poenget med versjonering bryter litt sammen.
2. rydde opp i package.json dependencies
Hovedpunktet er at alt som ligger der vil bli innstallert av appen som bruker komponenten deres. Og jeg mistenker at `less`, `mustashe`, `@fortawesome/XXXXX`, `lodash`, `nav-styled-components-theme`, `styled-components` og `react-syntax-highlighter` er ting som brukes for å generere dokumentasjons-siden, og ikke nødvendigvis noe konsumentene av komponenten trenger.

2020-05-20 10:43 UTC, Lillebo commented
Bare send meg eposten/brukernavnet ditt på npmjs.com Nuno - så kan jeg legge deg til slik at du kan publisere pakkene under navikt-orgen vår der 🙂

2020-05-22 09:15 UTC, NunoCardoso commented
Filopplasting er nå til https://www.npmjs.com/package/filopplasting 
dokumentasjonen er på https://www.npmjs.com/package/filopplasting-doc så at filopplasting har bare nødvendige avhengigheter

2020-05-28 09:40 UTC, Lillebo approved these changes
Ser greit ut for min del 👍

2020-05-28 10:04 UTC, KenAJoh requested changes
Hei, har vært flott hvis link til npm install, eller fks `npm i forhandsvisningsfil` har vært i Readme for begge pakkene

2020-06-03 05:09 UTC, KenAJoh approved these changes

2020-06-08 11:31 UTC, NunoCardoso commented
@nutgaard er det OK?

2020-06-08 12:14 UTC, nutgaard commented
Yup yup.

2020-06-08 12:14 UTC, nutgaard approved these changes

2020-06-08 12:31 UTC, merged