Mer moderne linting og formatering
navikt/aksel pull request #794
Opened 2020-10-01 15:54 UTC by andnorda

Her er et forsøk på å gjøre linting og formatinger både enklere og hakket bedre ved å oppgradere til noe mer moderne teknologi. 
- oppgradert eslint og bruker reglene til eslint-config-react-app
- lesshint byttet ut med stylelint
- la inn prettier

Håper det smaker!

2020-10-03 16:09 UTC, KenAJoh requested changes
Vurdere å ikke kjøre prettier på kode-eksemplene for veileder og veilederpanel da disse blir litt lange?
Ellers super PR 🎉 🎉

2020-10-03 16:09 UTC, KenAJoh commented on guideline-app/app/ui/components/left-navigation/LeftNavigation.js
> +                    <Undertekst>CSS</Undertekst>
Ser ut som denne linjen har mistet to stiler. "Tabell CSS" på nettsiden har ikke mellomrom lengre.

2020-10-05 08:01 UTC, andnorda commented
Jeg tenker at å rydde opp i kode-eksemplene kan gjøres når tar Den Store Dokumentasjon-migrasjonen ™️

2020-10-05 12:19 UTC, KenAJoh approved these changes

2020-10-05 12:19 UTC, merged