Legger til ny alertstripe for feilmeldinger
navikt/aksel pull request #94
Opened 2017-10-03 06:23 UTC by marthejs

Legger til nytt ikon og ny alertstripe for feilmeldinger.

2017-10-03 06:50 UTC, nutgaard requested changes

2017-10-03 06:50 UTC, nutgaard commented on packages/node_modules/nav-frontend-alertstriper/src/alertstripe.js
> +    'alertstripe--feil': type === 'feil',
Er ikke dette bare en fylt versjon av `advarsel`-typen?

2017-10-04 06:26 UTC, JohRus approved these changes

2017-10-04 08:45 UTC, nutgaard commented on packages/node_modules/nav-frontend-alertstriper/src/alertstripe.js
> +    'alertstripe--feil': type === 'feil',
Svar fra Sergio: 
"Hei, 

Riktig, det en "ikke fylt" versjon av alertstripe-advarsel ikon er annerldes og kan anses mer som en “stop” type melding. Men det er egentlig eneste forskjell. Jeg had nok følgt navn konvensjon vi har brukt tidligere men kanskje tilsette en parametre for stop ikonen (om det lar seg gjøre og er fornuftig). "

2017-10-04 10:39 UTC, nutgaard approved these changes

2017-10-04 11:46 UTC, merged